import { getVariablesFromEnv } from "../../env";
import { typeImplementsFn } from "../../evaluator/trait-checking";
import {
  BuiltinFunctions,
  BuiltinKeywords,
  exprIsAtom,
  exprIsFunctionCall,
  exprIsFunctionCallOf,
  type FnCallExpr,
} from "../../expr";
import {
  isArrayType,
  isObjectType,
  isSliceType,
  isStructType,
  isTupleType,
  isUnitType,
} from "../../types/guards";
import { isTempVariableName } from "../../utils";
import type { FunctionGenerationContext } from "../functions/context";
import {
  type CodeGenContext,
  getTypeString,
  getVariableNameForCodegen,
  getVariableTypeString,
  sanitizeForCIdentifier,
} from "../utils";
import { checkVariableIsClosureCaptured } from "./closures";
import { generateDeferredDupExpressions } from "./drop-dup";
import { generateExpr } from "./expr";

/**
 *
 * Initialization assignment
 */
export function generateInitializationAssignment(
  expr: FnCallExpr,
  indent: string,
  context: CodeGenContext
): string | undefined {
  const lhs = expr.args[0]!;
  const rhs = expr.args[1]!;

  // Debug: Log all := assignments in state machines
  const functionContext = context as FunctionGenerationContext;

  if (
    exprIsFunctionCall(lhs) &&
    exprIsFunctionCallOf(lhs, BuiltinKeywords.comptime, 1)
  ) {
    // compile-time variable
    return "";
  }

  // In state machine context, skip variable "load" expressions (localVar := stateMachineVar)
  // These are generated by the type checker to create local copies of variables
  // But in state machines, we access variables directly through sm->var_xxx
  if (functionContext.inStateMachine && exprIsAtom(lhs) && exprIsAtom(rhs)) {
    const lhsName = lhs.token.value;
    const rhsName = rhs.token.value;

    // Check if both refer to the same state machine variable
    // This handles cases like: b := b (creating a local copy)
    const lhsIsStateMachineVar =
      functionContext.stateMachineVariables &&
      Array.from(functionContext.stateMachineVariables.values()).some(
        (v) => v.name === lhsName
      );
    const rhsIsStateMachineVar =
      functionContext.stateMachineVariables &&
      Array.from(functionContext.stateMachineVariables.values()).some(
        (v) => v.name === rhsName
      );

    // Skip if both sides reference state machine variables with the same name
    // OR if we're trying to create a local copy of a state machine variable
    if (lhsName === rhsName && (lhsIsStateMachineVar || rhsIsStateMachineVar)) {
      // Self-assignment of state machine variable - skip to avoid redundant local copy

      return "";
    }
  }

  // Check if it's destructurings
  if (expr.$?.runtimeDestructurings) {
    const runtimeDestructurings = expr.$.runtimeDestructurings;
    const rhsCode = generateExpr(rhs, indent, context);
    const rhsType = rhs.$?.type;
    runtimeDestructurings.forEach(({ label, type, variableName }) => {
      // Sanitize the variable name for C
      const sanitizedVariableName = sanitizeForCIdentifier(
        variableName,
        type.isExtern === "c"
      );
      const varTypeAndName = getVariableTypeString(
        type,
        sanitizedVariableName,
        context
      );

      // Handle newtype destructuring - just use the value itself
      if (
        rhsType &&
        isStructType(rhsType) &&
        rhsType.isNewtype &&
        rhsType.fields.length === 1
      ) {
        const singleField = rhsType.fields[0];
        if (singleField && singleField.label === label) {
          // For newtype, destructuring the single field just returns the value itself
          context.emitter.emitLine(
            `${indent}${varTypeAndName} = ${rhsCode}; // Destructuring ${label} (newtype)`
          );
          return;
        }
      }

      let fieldName = label.match(/^\d+$/)
        ? `_${label}`
        : sanitizeForCIdentifier(label, type.isExtern === "c");

      if (rhsType && isTupleType(rhsType) && !label.match(/^\d+$/)) {
        const index = rhsType.fields.findIndex((el) => el.label === label);
        fieldName = index >= 0 ? `_${index}` : fieldName;
      }

      // Use -> for ref types (which are pointers), . for regular types
      const memberAccessOp = rhsType && isObjectType(rhsType) ? "->" : ".";

      context.emitter.emitLine(
        `${indent}${varTypeAndName} = ${rhsCode}${memberAccessOp}${fieldName}; // Destructuring ${label}`
      );
    });
    return "";
  }

  if (exprIsAtom(lhs)) {
    const varName = lhs.token.value;
    if (!lhs.$?.type) {
      return `// Error: No type information for variable ${varName}\n`;
    }

    // Check if the variable being assigned to is compile-time
    // If so, skip code generation (compile-time variables don't exist at runtime)
    if (lhs.$?.env) {
      const variables = getVariablesFromEnv(lhs.$.env, varName);
      if (
        variables.length > 0 &&
        variables[variables.length - 1]!.isCompileTimeOnly
      ) {
        return "";
      }
    }

    // To check if a variable is in the state machine, we need to:
    // 1. Look up the variable in the environment to get its ID
    // 2. Check if that ID is a key in stateMachineVariables map
    let isStateMachineVar = false;
    let varId: string | undefined;

    if (
      functionContext.inStateMachine &&
      functionContext.stateMachineVariables &&
      lhs.$?.env
    ) {
      // Get the variable from the environment
      const variables = getVariablesFromEnv(lhs.$.env, varName);
      if (variables.length > 0) {
        const variable = variables[variables.length - 1]!;
        // Check if this variable (or its owner if it's borrowing) is in state machine
        const idToCheck = variable.isOwningTheSameRcValueAs
          ? variable.isOwningTheSameRcValueAs.id
          : variable.id;

        if (functionContext.stateMachineVariables.has(idToCheck)) {
          isStateMachineVar = true;
          varId = idToCheck;
        }
      }
    }

    // Handle array initialization specially
    if (isArrayType(lhs.$.type)) {
      // Check if RHS is an array literal
      if (
        exprIsFunctionCall(rhs) &&
        exprIsFunctionCallOf(rhs, BuiltinKeywords.array)
      ) {
        // Direct initialization with array literal
        const rhsCode = generateExpr(rhs, indent, context);

        if (isStateMachineVar && varId) {
          // In state machine - assign to sm->var_xxx field
          context.emitter.emitLine(`${indent}sm->var_${varId} = ${rhsCode};`);
        } else {
          // Skip unit type variables (zero-sized types, optimized away like Rust)
          if (!isUnitType(lhs.$.type)) {
            const varTypeAndName = getVariableTypeString(
              lhs.$.type,
              varName,
              context
            );
            context.emitter.emitLine(
              `${indent}${varTypeAndName} = ${rhsCode};`
            );
          }
        }
      } else {
        // Copying from another array - use direct struct assignment
        // Handle temp variable assignment for Rc values
        let rhsCode: string;
        if (rhs.$?.variableName) {
          const tempVarName = getVariableNameForCodegen(
            rhs.$.variableName,
            rhs.$.env
          );

          const rhsExprCode = generateExpr(rhs, indent, context);

          // Generate temp variable assignment first (only if not in state machine)
          if (!isStateMachineVar) {
            const tempVarType = getVariableTypeString(
              rhs.$.type!,
              tempVarName,
              context
            );
            if (tempVarName !== rhsExprCode) {
              context.emitter.emitLine(
                `${indent}${tempVarType} = ${rhsExprCode};`
              );
            }
          }

          // Use temp variable for the main assignment
          rhsCode = tempVarName;
        } else {
          rhsCode = generateExpr(rhs, indent, context);
        }

        if (isStateMachineVar && varId) {
          // In state machine - assign to sm->var_xxx field
          context.emitter.emitLine(`${indent}sm->var_${varId} = ${rhsCode};`);
        } else {
          // Skip unit type variables (zero-sized types, optimized away like Rust)
          if (!isUnitType(lhs.$.type)) {
            const varTypeAndName = getVariableTypeString(
              lhs.$.type,
              varName,
              context
            );
            context.emitter.emitLine(
              `${indent}${varTypeAndName} = ${rhsCode};`
            );
          }
        }
      }
    } else {
      // Non-array initialization - use existing logic
      let rhsCode: string;

      const rhsIsClosureConstruction =
        exprIsFunctionCall(rhs) &&
        rhs.$?.closureFunctionValue &&
        rhs.$?.type &&
        typeImplementsFn(rhs.$.type);

      // Async blocks handle their own deferred dup expressions internally
      // (as part of capture struct construction in generateAsyncBlock)
      const rhsIsAsyncBlock =
        exprIsFunctionCall(rhs) &&
        exprIsFunctionCallOf(rhs, BuiltinFunctions.async);

      // If RHS has a temp variable name (e.g., for Rc values), we need to:
      // 1. First generate the RHS expression and assign it to the temp variable
      // 2. Then use the temp variable for the assignment
      // BUT: don't create temp variables for captured variables
      // ALSO: don't create temp variables if the temp var name is the same as the variable itself
      if (rhs.$?.variableName) {
        const tempVarName = getVariableNameForCodegen(
          rhs.$.variableName,
          rhs.$.env
        );

        const sanitizedVarName = getVariableNameForCodegen(varName, lhs.$.env);

        // Skip temp variable creation if temp var name matches the actual variable name
        // This prevents redundant declarations like "int32_t x = x;"
        if (tempVarName === sanitizedVarName) {
          // Just use the variable directly, no temp variable needed
          rhsCode = generateExpr(rhs, indent, context);

          // Handle deferred dup expressions even for simple variable references
          if (
            !rhsIsClosureConstruction &&
            !rhsIsAsyncBlock &&
            rhs.$?.deferredDupExpressions &&
            rhs.$.deferredDupExpressions.length > 0
          ) {
            generateDeferredDupExpressions(rhs, indent, functionContext);
            const dupExpr = rhs.$.deferredDupExpressions[0]!;
            if (exprIsFunctionCall(dupExpr) && dupExpr.$?.variableName) {
              rhsCode = getVariableNameForCodegen(
                dupExpr.$.variableName,
                dupExpr.$.env
              );
            }
          }
        } else if (
          exprIsAtom(rhs) &&
          tempVarName === getVariableNameForCodegen(rhs.token.value, rhs.$.env)
        ) {
          // Just use the variable directly, no temp variable needed
          rhsCode = generateExpr(rhs, indent, context);

          // Handle deferred dup expressions even for simple variable references
          if (
            !rhsIsClosureConstruction &&
            !rhsIsAsyncBlock &&
            rhs.$?.deferredDupExpressions &&
            rhs.$.deferredDupExpressions.length > 0
          ) {
            generateDeferredDupExpressions(rhs, indent, functionContext);
            const dupExpr = rhs.$.deferredDupExpressions[0]!;
            if (exprIsFunctionCall(dupExpr) && dupExpr.$?.variableName) {
              rhsCode = getVariableNameForCodegen(
                dupExpr.$.variableName,
                dupExpr.$.env
              );
            }
          }
        } else {
          if (
            exprIsAtom(rhs) &&
            functionContext.currentClosureCaptures &&
            functionContext.currentClosureCaptures.includes(rhs.token.value) &&
            rhs.$?.env &&
            functionContext.currentClosureCaptureFrameLevel !== undefined &&
            checkVariableIsClosureCaptured(
              rhs.token.value,
              rhs.$.env,
              functionContext.currentClosureCaptureFrameLevel
            )
          ) {
            // This is a captured variable, don't create a temp variable for it
            // Generate closure access directly
            const currentClosureType = functionContext.currentClosureType;
            if (currentClosureType && currentClosureType.isClosure) {
              const closureTypeEntry = Object.values(
                functionContext.types
              ).find((entry) => entry.type === currentClosureType);
              if (closureTypeEntry) {
                // Note: captureType is no longer on ClosureType, so we use a naming convention
                // The capture struct name follows the pattern: closure_type_name + "_capture"
                const captureStructName = `${closureTypeEntry.cName}_capture`;
                rhsCode = `((${captureStructName}*)closure_context->data)->${getVariableNameForCodegen(rhs.token.value, rhs.$.env)}`;
              } else {
                rhsCode = `closure_context->${getVariableNameForCodegen(rhs.token.value, rhs.$.env)}`;
              }
            } else {
              rhsCode = `closure_context->${getVariableNameForCodegen(rhs.token.value, rhs.$.env)}`;
            }
          } else {
            // Normal temp variable handling
            const rhsExprCode = generateExpr(rhs, indent, context);

            // Check if the RHS expression already generates the same temp variable
            // If so, don't generate a redundant assignment
            if (rhsExprCode.trim() !== tempVarName) {
              // Generate temp variable assignment first
              // Use convertedRuntimeType if available (e.g., comptime_string -> str)
              const effectiveType = rhs.$.convertedRuntimeType || rhs.$.type!;
              const tempVarType = getVariableTypeString(
                effectiveType,
                tempVarName,
                context
              );
              context.emitter.emitLine(
                `${indent}${tempVarType} = ${rhsExprCode};`
              );
            }

            // Handle deferred dup expressions for RHS
            // After generating the RHS temp variable, check if we need to dup it
            if (
              !rhsIsClosureConstruction &&
              !rhsIsAsyncBlock &&
              rhs.$?.deferredDupExpressions &&
              rhs.$.deferredDupExpressions.length > 0
            ) {
              generateDeferredDupExpressions(rhs, indent, functionContext);
              // Use the dup result variable instead of the original temp variable
              const dupExpr = rhs.$.deferredDupExpressions[0]!;
              if (exprIsFunctionCall(dupExpr) && dupExpr.$?.variableName) {
                rhsCode = getVariableNameForCodegen(
                  dupExpr.$.variableName,
                  dupExpr.$.env
                );
              } else {
                // Use temp variable for the main assignment
                rhsCode = tempVarName;
              }
            } else {
              // Use temp variable for the main assignment
              rhsCode = tempVarName;
            }
          }
        }
      } else {
        rhsCode = generateExpr(rhs, indent, context);

        // Handle deferred dup expressions for RHS without temp variable
        if (
          !rhsIsClosureConstruction &&
          !rhsIsAsyncBlock &&
          rhs.$?.deferredDupExpressions &&
          rhs.$.deferredDupExpressions.length > 0
        ) {
          generateDeferredDupExpressions(rhs, indent, functionContext);
          // Use the dup result variable
          const dupExpr = rhs.$.deferredDupExpressions[0]!;
          if (exprIsFunctionCall(dupExpr) && dupExpr.$?.variableName) {
            rhsCode = getVariableNameForCodegen(
              dupExpr.$.variableName,
              dupExpr.$.env
            );
          }
        }
      }

      // Special handling for slice initialization.
      if (isSliceType(lhs.$.type)) {
        const sliceType = lhs.$.type; // Get the slice type directly

        if (isStateMachineVar && varId) {
          // In state machine - assign to sm->var_xxx field
          context.emitter.emitLine(`${indent}sm->var_${varId} = ${rhsCode};`);
        } else {
          // Skip unit type variables (zero-sized types, optimized away like Rust)
          if (!isUnitType(sliceType)) {
            const varTypeAndName = getVariableTypeString(
              sliceType,
              varName,
              context
            );
            context.emitter.emitLine(
              `${indent}${varTypeAndName} = ${rhsCode};`
            );
          }
        }
      } else {
        // Normal initialization
        if (isStateMachineVar && varId) {
          // In state machine - assign to sm->var_xxx field
          context.emitter.emitLine(`${indent}sm->var_${varId} = ${rhsCode};`);
        } else {
          // Check if RHS is a temp variable with a registered async struct name
          const rhsIsTempVar = isTempVariableName(
            rhs.$!.env.modulePath,
            rhsCode.trim()
          );
          let cTypeString: string;

          if (rhsIsTempVar && context.tempVarAsyncStructNames) {
            const asyncStructName = context.tempVarAsyncStructNames.get(
              rhsCode.trim()
            );
            if (asyncStructName) {
              cTypeString = `${asyncStructName}*`;
            } else {
              cTypeString = getTypeString(lhs.$.type, context);
            }
          } else {
            cTypeString = getTypeString(lhs.$.type, context);
          }

          // Skip unit type variables (zero-sized types, optimized away like Rust)
          if (!isUnitType(lhs.$.type)) {
            context.emitter.emitLine(
              `${indent}${cTypeString} ${getVariableNameForCodegen(varName, lhs.$.env)} = ${rhsCode};`
            );
          }
        }
      }
    }
    return "";
  }
}
