import { Environment } from "../../env";
import { formatErrorMessage } from "../../error";
import {
  BuiltinFunctions,
  BuiltinKeywords,
  Expr,
  exprIsAtom,
  exprIsFunctionCall,
  exprIsFunctionCallOf,
  exprToString,
  FuncCallExpr,
} from "../../expr";
import { generateExprFromCode } from "../../parser";
import {
  createEnumType,
  EnumType,
  EnumVariant,
  ModuleElement,
  typeContainsARCType,
} from "../../types";
import { createTypeValue, isFunctionValue } from "../../value";
import { EvaluatorContext } from "../context";
import { isValidVariableName } from "../utils";
import { evaluateElementType } from "./element";
import { evaluateTupleElementsType } from "./tuple";
import { validateDisposeFunction } from "./validation";

/**
 * Helper function to parse and evaluate a Yo code string in the context of an enum
 */
function parseAndEvaluateExprInEnum(
  code: string,
  enumType: EnumType,
  env: Environment,
  context: EvaluatorContext
): { expr: Expr; env: Environment } {
  const expr = generateExprFromCode(code);

  // Evaluate the expression with the enum as the SelfType
  const evaluatedExpr = context.evaluateExpression({
    expr,
    env,
    context: {
      ...context,
      SelfType: enumType,
    },
  });

  if (!evaluatedExpr.$) {
    throw new Error(
      `Failed to evaluate auto-generated expression: ${exprToString(expr)}`
    );
  }

  return { expr: evaluatedExpr, env: evaluatedExpr.$.env };
}

/**
 * Generate drop function code for an enum type
 */
function generateDropFunctionCode(enumType: EnumType): string {
  const hasDisposeFunction = enumType.module.elements.some(
    (element) => element.label === BuiltinFunctions.dispose[0]
  );

  // For enums, we need to handle each variant that may contain ARC types
  const variantsToHandle = enumType.variants.filter(
    (variant) =>
      variant.elements &&
      variant.elements.some((element) => typeContainsARCType(element.type))
  );

  if (!variantsToHandle.length) {
    return `((fn(self : Self) -> unit) {
  __yo_decr_rc(self${hasDisposeFunction ? `, Self.dispose` : ""});
  ()
})`;
  }

  return `((fn(self : Self) -> unit) {
  match(
    self,
    ${variantsToHandle
      .map((variant) => {
        const destructurings = variant
          .elements!.filter(
            (element) =>
              !element.isCompileTimeOnly && typeContainsARCType(element.type)
          )
          .map((element) => element.label);

        return `.${variant.name}(${variant.elements!.map((element) => element.label)}) => {
      ${destructurings.map((label) => `(${BuiltinFunctions.___drop[0]!})(${label});`).join("\n")}
    }`;
      })
      .join(", ")}${
      variantsToHandle.length === enumType.variants.length
        ? ""
        : `,
    _ => ()`
    }
  );
  __yo_decr_rc(self${hasDisposeFunction ? `, Self.dispose` : ""});
  ()
})`;
}

/**
 * Check if an enum needs an auto-generated drop function
 */
function needsAutoGeneratedDropFunction(enumType: EnumType): boolean {
  // Check if drop function already exists in module elements
  const hasExplicitDrop = enumType.module.elements.some(
    (element) => element.label === BuiltinFunctions.___drop[0]
  );

  if (hasExplicitDrop) {
    return false;
  }

  // Check if this is a Linear type either from the enum's own type or from expectedType
  return typeContainsARCType(enumType);
}

export function evaluateEnumType({
  expr,
  env,
  context,
}: {
  expr: FuncCallExpr;
  env: Environment;
  context: EvaluatorContext;
}): FuncCallExpr {
  if (!exprIsFunctionCallOf(expr, BuiltinKeywords.enum)) {
    throw formatErrorMessage({
      token: expr.token,
      errorMessage: `Expected "enum", got:\n${exprToString(expr)}`,
    });
  }

  // Create enumType with empty variants
  const enumType = createEnumType(env);

  // Evaluate the variants
  const variants: EnumVariant[] = enumType.variants;
  const moduleElements: ModuleElement[] = enumType.module.elements;

  for (let i = 0; i < expr.args.length; i++) {
    const enumArg = expr.args[i]!;

    // comptime fields
    // eg:
    //   ~~Self.new = (((lhs: Self, rhs: i32) -> i32) {})~~
    //   new :: (((lhs: Self, rhs: i32) -> i32) {})
    if (
      exprIsFunctionCall(enumArg) &&
      (exprIsFunctionCallOf(enumArg, "::", 2) ||
        exprIsFunctionCallOf(enumArg, "=", 2) ||
        exprIsFunctionCallOf(enumArg, "?=", 2))
    ) {
      const arg = enumArg;

      const { type, env: nextEnv } = evaluateElementType({
        expr: arg,
        env,
        tupleElementIndex: i,
        context: { ...context, SelfType: enumType },
        forType: "enum",
      });

      // Check if there is duplicate labels
      const duplicateLabel = moduleElements.find(
        (element) => element.label === type.label
      );
      if (duplicateLabel) {
        throw formatErrorMessage({
          token: arg.token,
          errorMessage: `Duplicate label "${type.label}" in enum`,
        });
      }

      // Check if it duplicates with the existing variant names
      if (variants.some((v) => v.name === type.label)) {
        throw formatErrorMessage({
          token: arg.token,
          errorMessage: `Duplicate label "${type.label}" in enum variants`,
        });
      }

      if (!type.isCompileTimeOnly) {
        throw formatErrorMessage({
          token: arg.token,
          errorMessage: `Expected compile-time only field, got:\n${exprToString(
            type.exprs.expr
          )}`,
        });
      }

      // Disallow to have the default value for enum type fields.
      if (type.defaultValue) {
        throw formatErrorMessage({
          token: type.exprs.defaultValueExpr?.token ?? type.exprs.expr.token,
          errorMessage: `Enum type cannot have default value for its elements.`,
        });
      }

      // ___drop function
      if (type.label === BuiltinFunctions.___drop[0]) {
        throw formatErrorMessage({
          token: arg.token,
          errorMessage: `The label "${BuiltinFunctions.___drop[0]}()" is reserved for the auto-generated drop function. You cannot define it as a compile-time-only element.`,
        });
      }

      // dispose function
      // Verify the disposeFunction has the correct type.
      // fn(self : Self) -> unit
      if (type.label === BuiltinFunctions.dispose[0]) {
        validateDisposeFunction(type as ModuleElement, arg.token);
      }
      moduleElements.push(type as ModuleElement);
      env = nextEnv;
    }

    // Enum variant
    else {
      if (exprIsAtom(enumArg)) {
        const variantName = enumArg.token.value;
        if (!isValidVariableName(enumArg)) {
          throw formatErrorMessage({
            token: enumArg.token,
            errorMessage: `Expected identifier for enum variant, got:\n${exprToString(
              enumArg
            )}`,
          });
        }
        variants.push({
          name: variantName,
        });

        // TODO: Check duplicates
      } else {
        if (exprIsFunctionCallOf(enumArg, ":")) {
          throw formatErrorMessage({
            token: enumArg.token,
            errorMessage: `Enum variant with : is not implemented yet`,
          });
        }
        if (!isValidVariableName(enumArg.func)) {
          throw formatErrorMessage({
            token: enumArg.func.token,
            errorMessage: `Expected identifier for enum variant, got:\n${exprToString(
              enumArg.func
            )}`,
          });
        }
        const variantName = enumArg.func.token.value;

        const { type: tupleType, env: nextEnv } = evaluateTupleElementsType({
          args: enumArg.args,
          env,
          context: {
            ...context,
            SelfType: enumType,
          },
          forType: "enum",
        });
        env = nextEnv;

        // We disallow to have isCompileTimeOnly for enum variant elements.
        // Because enum variant fields cannot be marked as compile-time only.
        for (let i = 0; i < tupleType.elements.length; i++) {
          const element = tupleType.elements[i]!;
          // QUESTION: Should we allow compile-time only field in enum variant?
          // If yes, should we require it to have assignedValue?
          if (element.isCompileTimeOnly) {
            throw formatErrorMessage({
              token: element.exprs.expr.token,
              errorMessage: `Enum variant element cannot be compile-time only, got:\n${exprToString(
                element.exprs.expr
              )}`,
            });
          }
        }

        variants.push({
          name: variantName,
          elements: tupleType.elements,
        });
      }
    }
  }

  // Auto-generate ___drop function if not provided and it's needed
  if (needsAutoGeneratedDropFunction(enumType)) {
    const dropFunctionCode = generateDropFunctionCode(enumType);
    // console.log(dropFunctionCode);

    const { expr: dropFunctionExpr, env: nextEnv } = parseAndEvaluateExprInEnum(
      dropFunctionCode,
      enumType,
      env,
      context
    );

    // Extract the function value from the right-hand side of the :: assignment
    if (exprIsFunctionCall(dropFunctionExpr)) {
      const functionExpr = dropFunctionExpr;
      if (
        functionExpr.$ &&
        functionExpr.$.value &&
        isFunctionValue(functionExpr.$.value)
      ) {
        // The code below is necessary for the C code generator to make the ___drop function to have a more descriptive name.
        functionExpr.$.value.funcId += "___drop";

        // Add the drop function to the enum's module elements
        const dropModuleElement: ModuleElement = {
          label: BuiltinFunctions.___drop[0]!,
          type: functionExpr.$.type,
          assignedValue: functionExpr.$.value,
          isCompileTimeOnly: true,
          isImplicit: false,
          exprs: {
            expr: dropFunctionExpr,
            labelExpr: dropFunctionExpr.args[0],
            typeExpr: undefined,
            defaultValueExpr: undefined,
            assignedValueExpr: functionExpr,
          },
        };
        enumType.module.elements.push(dropModuleElement);
      }
    }

    env = nextEnv;
  }

  /*
  // QUESTION: Should we add such constraint?
  // Validate that ref enums must have at least one variant with members
  if (isReferenceSemantics) {
    const hasVariantWithMembers = variants.some(
      (variant) => variant.elements && variant.elements.length > 0
    );

    if (!hasVariantWithMembers) {
      throw formatErrorMessage({
        token: expr.token,
        errorMessage: `ref enum must have at least one variant with members. All variants in this enum have no members, so it should be a regular enum instead of ref enum.`,
      });
    }
  }
  */

  const enumTypeValue = createTypeValue(enumType);
  expr.$ = {
    env,
    value: enumTypeValue,
    type: enumTypeValue.type,
    pathCollection: [],
  };

  // Append more information to "enum" token.
  expr.func.$ = expr.$;
  return expr;
}
