import { Environment } from "../../env";
import { formatErrorMessage } from "../../error";
import {
  BuiltinKeywords,
  Expr,
  exprIsAtom,
  exprIsFunctionCall,
  exprIsFunctionCallOf,
  exprToString,
  FuncCallExpr,
} from "../../expr";
import Parser from "../../parser";
import {
  createEnumType,
  EnumType,
  EnumVariant,
  isLinearOrType0Type,
  ModuleElement,
  typeOfType,
} from "../../types";
import { randomId } from "../../utils";
import { createTypeValue } from "../../value";
import { EvaluatorContext } from "../context";
import { isValidVariableName } from "../utils";
import { evaluateElementType } from "./element";
import { evaluateTupleElementsType } from "./tuple";

/**
 * Helper function to parse and evaluate a Yo code string in the context of an enum
 */
function parseAndEvaluateExprInEnum(
  code: string,
  enumType: EnumType,
  env: Environment,
  context: EvaluatorContext
): { expr: Expr; env: Environment } {
  // Create a parser for the code string
  const parser = new Parser({
    modulePath: `auto-generated://${randomId()}`,
    inputString: code,
  });

  // Get the parsed expressions
  const program = parser.getProgram();
  if (program.length !== 1) {
    throw new Error(
      `Expected exactly one expression from parsed code, got ${program.length}`
    );
  }

  const expr = program[0]!;

  // Evaluate the expression with the enum as the SelfType
  const evaluatedExpr = context.evaluateExpression({
    expr,
    env,
    context: {
      ...context,
      SelfType: enumType,
    },
  });

  if (!evaluatedExpr.$) {
    throw new Error(
      `Failed to evaluate auto-generated expression: ${exprToString(expr)}`
    );
  }

  return { expr: evaluatedExpr, env: evaluatedExpr.$.env };
}

/**
 * Generate drop function code for an enum type using match expression
 */
function generateDropFunctionCode(enumType: EnumType): string {
  const matchCases = enumType.variants
    .map((variant) => {
      if (variant.elements && variant.elements.length > 0) {
        // For variants with data, destructure them
        const fieldDestructure = variant.elements
          .filter((element) => isLinearOrType0Type(element.type))
          .map((element) => element.label)
          .join(", ");

        if (fieldDestructure) {
          return `    .${variant.name} => { ${fieldDestructure} } := self`;
        } else {
          return `    .${variant.name} => ()`; // No linear fields to drop
        }
      } else {
        // For variants without data
        return `    .${variant.name} => ()`;
      }
    })
    .join(",\n");

  return `drop :: (((self: Self) -> unit)
  match(self,
${matchCases}
  ))`;
}

/**
 * Check if an enum needs an auto-generated drop function
 */
function needsAutoGeneratedDropFunction(
  enumType: EnumType,
  context: EvaluatorContext
): boolean {
  // Check if drop function already exists in module elements
  const hasExplicitDrop = enumType.module.elements.some(
    (element) => element.label === "drop"
  );

  if (hasExplicitDrop) {
    return false;
  }

  // Check if this is a Linear type either from the enum's own type or from expectedType
  const enumTypeOfType = typeOfType(enumType);
  const isLinearFromEnumType = isLinearOrType0Type(enumTypeOfType);

  // Also check if the expectedType (from initialization assignment) is Linear
  const isLinearFromExpectedType = context.expectedType
    ? isLinearOrType0Type(context.expectedType.type)
    : false;

  return isLinearFromEnumType || isLinearFromExpectedType;
}

export function evaluateEnumType({
  expr,
  env,
  context,
}: {
  expr: FuncCallExpr;
  env: Environment;
  context: EvaluatorContext;
}): FuncCallExpr {
  if (!exprIsFunctionCallOf(expr, BuiltinKeywords.enum)) {
    throw formatErrorMessage({
      token: expr.token,
      errorMessage: `Expected "enum", got:\n${exprToString(expr)}`,
    });
  }

  // Create enumType with empty variants
  const enumType = createEnumType(env);

  // Evaluate the variants
  const variants: EnumVariant[] = enumType.variants;
  const moduleElements: ModuleElement[] = enumType.module.elements;

  for (let i = 0; i < expr.args.length; i++) {
    const enumArg = expr.args[i]!;

    // comptime fields
    // eg:
    //   ~~Self.new = (((lhs: Self, rhs: i32) -> i32) {})~~
    //   new :: (((lhs: Self, rhs: i32) -> i32) {})
    if (
      exprIsFunctionCall(enumArg) &&
      (exprIsFunctionCallOf(enumArg, "::", 2) ||
        exprIsFunctionCallOf(enumArg, "=", 2) ||
        exprIsFunctionCallOf(enumArg, "?=", 2))
    ) {
      const arg = enumArg;
      const { type, env: nextEnv } = evaluateElementType({
        expr: arg,
        env,
        tupleElementIndex: i,
        context: { ...context, SelfType: enumType },
        forType: "enum",
      });

      // Check if there is duplicate labels
      const duplicateLabel = moduleElements.find(
        (element) => element.label === type.label
      );
      if (duplicateLabel) {
        throw formatErrorMessage({
          token: arg.token,
          errorMessage: `Duplicate label "${type.label}" in enum`,
        });
      }

      // Check if it duplicates with the existing variant names
      if (variants.some((v) => v.name === type.label)) {
        throw formatErrorMessage({
          token: arg.token,
          errorMessage: `Duplicate label "${type.label}" in enum variants`,
        });
      }

      if (!type.isCompileTimeOnly) {
        throw formatErrorMessage({
          token: arg.token,
          errorMessage: `Expected compile-time only field, got:\n${exprToString(
            type.exprs.expr
          )}`,
        });
      }

      // Disallow to have the default value for enum type fields.
      if (type.defaultValue) {
        throw formatErrorMessage({
          token: type.exprs.defaultValueExpr?.token ?? type.exprs.expr.token,
          errorMessage: `Enum type cannot have default value for its elements.`,
        });
      }

      moduleElements.push(type as ModuleElement);
      env = nextEnv;
    }

    // Enum variant
    else {
      if (exprIsAtom(enumArg)) {
        const variantName = enumArg.token.value;
        if (!isValidVariableName(enumArg)) {
          throw formatErrorMessage({
            token: enumArg.token,
            errorMessage: `Expected identifier for enum variant, got:\n${exprToString(
              enumArg
            )}`,
          });
        }
        variants.push({
          name: variantName,
        });

        // TODO: Check duplicates
      } else {
        if (exprIsFunctionCallOf(enumArg, ":")) {
          throw formatErrorMessage({
            token: enumArg.token,
            errorMessage: `Enum variant with : is not implemented yet`,
          });
        }
        if (!isValidVariableName(enumArg.func)) {
          throw formatErrorMessage({
            token: enumArg.func.token,
            errorMessage: `Expected identifier for enum variant, got:\n${exprToString(
              enumArg.func
            )}`,
          });
        }
        const variantName = enumArg.func.token.value;

        const { type: tupleType, env: nextEnv } = evaluateTupleElementsType({
          args: enumArg.args,
          env,
          context: {
            ...context,
            SelfType: enumType,
          },
          forType: "enum",
        });
        env = nextEnv;

        // We disallow to have isCompileTimeOnly for enum variant elements.
        // Because enum variant fields cannot be marked as compile-time only.
        for (let i = 0; i < tupleType.elements.length; i++) {
          const element = tupleType.elements[i]!;
          // QUESTION: Should we allow compile-time only field in enum variant?
          // If yes, should we require it to have assignedValue?
          if (element.isCompileTimeOnly) {
            throw formatErrorMessage({
              token: element.exprs.expr.token,
              errorMessage: `Enum variant element cannot be compile-time only, got:\n${exprToString(
                element.exprs.expr
              )}`,
            });
          }
        }

        variants.push({
          name: variantName,
          elements: tupleType.elements,
        });
      }
    }
  }

  // Auto-generate drop function if not provided and enum is linear
  if (needsAutoGeneratedDropFunction(enumType, context)) {
    try {
      const dropFunctionCode = generateDropFunctionCode(enumType);

      const { expr: dropExpr, env: nextEnv } = parseAndEvaluateExprInEnum(
        dropFunctionCode,
        enumType,
        env,
        context
      );

      // Extract the function value from the right-hand side of the :: assignment
      if (
        exprIsFunctionCall(dropExpr) &&
        exprIsFunctionCallOf(dropExpr, "::", 2)
      ) {
        const functionExpr = dropExpr.args[1]!; // The function is on the RHS of ::
        if (functionExpr.$ && functionExpr.$.value) {
          // Add the drop function to the enum's module elements
          const dropModuleElement: ModuleElement = {
            label: "drop",
            type: functionExpr.$.type,
            assignedValue: functionExpr.$.value,
            isCompileTimeOnly: true,
            isImplicit: false,
            exprs: {
              expr: dropExpr,
              labelExpr: dropExpr.args[0],
              typeExpr: undefined,
              defaultValueExpr: undefined,
              assignedValueExpr: functionExpr,
            },
          };
          enumType.module.elements.push(dropModuleElement);
        }
      }

      env = nextEnv;
    } catch (error) {
      // If auto-generation fails, we continue without the drop function
      // This prevents breaking existing code that doesn't need RAII
      console.warn(`Failed to auto-generate drop function for enum:`);
      console.warn(error);
    }
  }

  const enumTypeValue = createTypeValue(enumType);
  expr.$ = {
    env,
    value: enumTypeValue,
    type: enumTypeValue.type,
    isMutable: false,
    pathCollection: [],
  };

  // Append more information to "enum" token.
  expr.func.$ = expr.$;
  return expr;
}
