import { Environment } from "../../env";
import { formatErrorMessage } from "../../error";
import {
  BuiltinKeywords,
  Expr,
  exprIsFunctionCall,
  exprIsFunctionCallOf,
  exprToString,
  FuncCallExpr,
} from "../../expr";
import { generateExprFromCode } from "../../parser";
import {
  createStructType,
  isLinearOrType0Type,
  isStructType,
  ModuleElement,
  StructType,
  TupleElement,
  typeOfType,
} from "../../types";
import {
  areValuesEqual,
  createTypeValue,
  isModuleValue,
  isTypeValue,
} from "../../value";
import { EvaluatorContext } from "../context";
import { evaluateElementType } from "./element";

/**
 * Helper function to parse and evaluate a Yo code string in the context of a struct
 */
function parseAndEvaluateExprInStruct(
  code: string,
  structType: StructType,
  env: Environment,
  context: EvaluatorContext
): { expr: Expr; env: Environment } {
  const expr = generateExprFromCode(code);

  // Evaluate the expression with the struct as the SelfType
  const evaluatedExpr = context.evaluateExpression({
    expr,
    env,
    context: {
      ...context,
      SelfType: structType,
    },
  });

  if (!evaluatedExpr.$) {
    throw new Error(
      `Failed to evaluate auto-generated expression: ${exprToString(expr)}`
    );
  }

  return { expr: evaluatedExpr, env: evaluatedExpr.$.env };
}

/**
 * Generate drop function code for a struct type
 */
function generateDropFunctionCode(structType: StructType): string {
  const destructurePattern = structType.elements
    .filter(
      (element) =>
        !element.isCompileTimeOnly &&
        isLinearOrType0Type(typeOfType(element.type))
    )
    .map((element) => element.label)
    .join(", ");

  // If no fields to destructure, just create an empty function
  if (!destructurePattern) {
    return `drop :: (((self: Self) -> unit)
  () // No fields to drop
)`;
  }

  return `drop :: (((self: Self) -> unit) {
  { ${destructurePattern} } := self;
})`;
}

/**
 * Check if a struct needs an auto-generated drop function
 */
function needsAutoGeneratedDropFunction(
  structType: StructType,
  context: EvaluatorContext
): boolean {
  // Check if drop function already exists in module elements
  const hasExplicitDrop = structType.module.elements.some(
    (element) => element.label === "drop"
  );

  if (hasExplicitDrop) {
    return false;
  }

  // Check if this is a Linear type either from the struct's own type or from expectedType
  const structTypeOfType = typeOfType(structType);
  const isLinearFromStructType = isLinearOrType0Type(structTypeOfType);

  // Also check if the expectedType (from initialization assignment) is Linear
  const isLinearFromExpectedType = context.expectedType
    ? isLinearOrType0Type(context.expectedType.type)
    : false;

  return isLinearFromStructType || isLinearFromExpectedType;
}

export function evaluateStructType({
  expr,
  env,
  context,
}: {
  expr: FuncCallExpr;
  env: Environment;
  context: EvaluatorContext;
}): FuncCallExpr {
  if (!exprIsFunctionCallOf(expr, BuiltinKeywords.struct)) {
    throw formatErrorMessage({
      token: expr.token,
      errorMessage: `Expected "struct", got:\n${exprToString(expr)}`,
    });
  }

  // Create structType with empty elements
  // This is used as the SelfType for the following evaluations.
  const structType = createStructType(env);
  const elements = structType.elements;

  for (let i = 0; i < expr.args.length; i++) {
    const arg = expr.args[i]!;

    // spread operator for extending another struct type or module value.
    if (exprIsFunctionCall(arg) && exprIsFunctionCallOf(arg, "...", 1)) {
      const extendedExpr = arg.args[0]!;
      // Evaluate the extended struct expression

      const evaluatedExtendedExpr = context.evaluateExpression({
        expr: extendedExpr,
        env,
        context: {
          ...context,
          SelfType: structType,
        },
      });

      if (!evaluatedExtendedExpr.$) {
        throw formatErrorMessage({
          token: extendedExpr.token,
          errorMessage: `Failed to evaluate the extended expression: ${exprToString(extendedExpr)}`,
        });
      }

      // Check if it's a struct type or module value
      const extendedExprValue = evaluatedExtendedExpr.$.value;

      if (
        isTypeValue(extendedExprValue) &&
        isStructType(extendedExprValue.value)
      ) {
        const extendedStructType = extendedExprValue.value;

        // Iterate over the elements of the extended struct
        for (const extendedStructElement of extendedStructType.elements) {
          // Check if there is duplicate labels
          // If yes, then override the element
          const duplicateLabelIndex = elements.findIndex(
            (e) => e.label === extendedStructElement.label
          );
          if (duplicateLabelIndex >= 0) {
            // Override the existing one.
            elements[duplicateLabelIndex] = extendedStructElement;
          } else {
            // Add the element to the struct
            elements.push(extendedStructElement);
          }
        }
      } else if (isModuleValue(extendedExprValue)) {
        const moduleValue = extendedExprValue;
        const moduleType = moduleValue.type;
        for (let i = 0; i < moduleType.elements.length; i++) {
          const element = moduleType.elements[i]!;
          // Check if there is duplicate labels
          // If yes, then override the element
          let duplicateLabelIndex = elements.findIndex(
            (e) => e.label === element.label
          );
          if (duplicateLabelIndex >= 0) {
            throw formatErrorMessage({
              token: extendedExpr.token,
              errorMessage: `Duplicate label "${element.label}" in struct extension from module value`,
            });
          }

          duplicateLabelIndex = structType.module.elements.findIndex(
            (e) => e.label === element.label
          );
          if (duplicateLabelIndex >= 0) {
            const existingModuleElement =
              structType.module.elements[duplicateLabelIndex];

            // Meet the same module element, so we skip
            if (
              existingModuleElement?.assignedValue &&
              element.assignedValue &&
              areValuesEqual(
                {
                  value: existingModuleElement.assignedValue,
                  env: env,
                },
                { value: element.assignedValue, env: env }
              )
            ) {
              continue;
            }

            throw formatErrorMessage({
              token: extendedExpr.token,
              errorMessage: `Duplicate label "${element.label}" in struct extension from module value`,
            });
          }

          structType.module.elements.push({
            ...element,
            assignedValue: moduleValue.elements[i],
          });
        }
      } else {
        throw formatErrorMessage({
          token: extendedExpr.token,
          errorMessage: `Expected a struct type or module value for extending, got ${exprToString(
            extendedExpr
          )}`,
        });
      }
    }
    // tuple element
    else {
      const { type, env: nextEnv } = evaluateElementType({
        expr: arg,
        env,
        tupleElementIndex: i,
        context: { ...context, SelfType: structType },
        forType: "struct",
      });

      // Check if there is duplicate labels
      const duplicateLabel = elements.find(
        (element) => element.label === type.label
      );
      if (duplicateLabel) {
        throw formatErrorMessage({
          token: exprIsFunctionCall(arg)
            ? (arg.args[0]?.token ?? arg.token)
            : arg.token,
          errorMessage: `Duplicate label "${type.label}" in struct`,
        });
      }

      if (type.isCompileTimeOnly) {
        const moduleElement = type as ModuleElement;
        structType.module.elements.push(moduleElement);
      } else {
        elements.push(type as TupleElement);
      }

      env = nextEnv;
    }
  }

  // Auto-generate drop function if not provided and struct is linear
  if (needsAutoGeneratedDropFunction(structType, context)) {
    const dropFunctionCode = generateDropFunctionCode(structType);

    const { expr: dropExpr, env: nextEnv } = parseAndEvaluateExprInStruct(
      dropFunctionCode,
      structType,
      env,
      context
    );

    // Extract the function value from the right-hand side of the :: assignment
    if (
      exprIsFunctionCall(dropExpr) &&
      exprIsFunctionCallOf(dropExpr, "::", 2)
    ) {
      const functionExpr = dropExpr.args[1]!; // The function is on the RHS of ::
      if (functionExpr.$ && functionExpr.$.value) {
        // Add the drop function to the struct's module elements
        const dropModuleElement: ModuleElement = {
          label: "drop",
          type: functionExpr.$.type,
          assignedValue: functionExpr.$.value,
          isCompileTimeOnly: true,
          isImplicit: false,
          exprs: {
            expr: dropExpr,
            labelExpr: dropExpr.args[0],
            typeExpr: undefined,
            defaultValueExpr: undefined,
            assignedValueExpr: functionExpr,
          },
        };
        structType.module.elements.push(dropModuleElement);
      }
    }

    env = nextEnv;
  }

  const structTypeValue = createTypeValue(structType);
  expr.$ = {
    env,
    type: structTypeValue.type,
    value: structTypeValue,
    isMutable: false,
    pathCollection: [],
  };

  // Append more information to "struct" token.
  expr.func.$ = expr.$;
  return expr;
}
