import type { Environment } from "../../env";
import { getVariablesFromEnv } from "../../env";
import { formatErrorMessage } from "../../error";
import {
  attachTempVariableToExpr,
  exprIsAtom,
  exprIsFunctionCallOf,
  exprToString,
  type FnCallExpr,
} from "../../expr";
import { TokenType, type Token } from "../../token";
import { areTypesCompatible } from "../../types/compatibility";
import type { EnumType, TypeField } from "../../types/definitions";
import { getValueOfSomeTypeFromEnv } from "../../types/env-lookup";
import {
  isEnumType,
  isFunctionType,
  isReferenceEnumType,
  isSourceNamespaceType,
  isPtrType,
  isSomeType,
  isStructType,
  isTraitType,
  isTupleType,
  isUnionType,
} from "../../types/guards";
import { typeToString } from "../../types/utils";
import {
  isImplicitlyUnsafeCapableFile,
  isAutoGeneratedExpansion,
} from "../memory-safety";
import {
  createEnumValue,
  createTypeValue,
  createUnknownValue,
  isArrayValue,
  isEnumValue,
  isFunctionValue,
  isStructValue,
  isPtrValue,
  isTraitValue,
  isTupleValue,
  isTypeValue,
  isUnknownValue,
  type Value,
} from "../../value";
import type { EvaluatorContext } from "../context";
import { isValidVariableName } from "../utils";
import {
  findAssociatedTypeFromGenericImpls,
  findMethodFromGenericImplForTrait,
  findMethodsFromGenericImpls,
} from "../values/impl";
import { evaluateExpression } from "./expr";

/**
 * Kind-constraint refinements of `Type`. Used in `generic(T : Type.Struct, ...)`
 * positions. Each refinement resolves to the same `TypeHierarchyType` value
 * `Type` itself returns — the kind is documentation/intent today, with
 * future enforcement (reject non-struct bindings) tracked separately. See
 * plans/EXPLICIT_EFFECTS.md §9.8.
 */
const TYPE_KIND_REFINEMENTS = new Set([
  "Struct",
  "Enum",
  "Union",
  "Trait",
  "Function",
]);

/**
 * A payload-free variant of a reference-semantics enum (`ref(enum(UnitVal, …))`)
 * still heap-allocates: `generateComptimeValue` emits
 * `__yo_new_<Enum>_<Variant>()` (src/codegen/exprs/comptime-value.ts:149-154),
 * which mallocs with `ref_count = 1`. The expression therefore OWNS an RC
 * value, exactly like the payload-carrying form `E.IntVal(v : …)` — that form
 * is a function call and gets its owning temp from the call path
 * (src/evaluator/calls/function.ts:2555).
 *
 * Without a temp variable the allocation is never registered at the enclosing
 * begin-block frame, so `getVariablesNeedingDrop` (src/env.ts:2272) never sees
 * it, no `___drop` is emitted, and an inline `f(E.UnitVal)` leaks the object
 * (the callee treats the parameter as borrowed and dups whatever it retains).
 *
 * Deliberately NOT `typeContainsRcType(expr.$.type)`: that is also true of a
 * VALUE enum whose *other* variants carry RC payloads (`Option(String)`,
 * `Result(…)`), whose payload-free variant materializes as a `{ .tag = … }`
 * compound literal and allocates nothing. An owning temp there is pure
 * overhead on the most common expression shape in std — and it makes
 * `(x : Option(String)) ?= Option(String).None` fail the not-consumed gate.
 *
 * The "some variant has fields" conjunct mirrors `canOptimizeAsSimpleEnum`
 * (src/codegen/utils/index.ts:961): an all-payload-free enum collapses to a
 * plain C enum constant (comptime-value.ts:129-133) and also allocates nothing.
 */
function attachOwnedTempForRcUnitVariant(
  expr: FnCallExpr,
  enumType: EnumType
): void {
  if (!expr.$ || !isReferenceEnumType(enumType)) {
    return;
  }
  const hasPayloadVariant = enumType.variants.some(
    (variant) => !!variant.fields && variant.fields.length > 0
  );
  if (!hasPayloadVariant) {
    return;
  }
  attachTempVariableToExpr(expr, true);
}

/**
 * Phase P (THREAD_SAFETY): Enforce `_`-prefix field visibility.
 * A field whose name starts with `_` is accessible only within the file
 * that defines the containing type. Auto-generated expansions inherit
 * the privilege of their expansion site.
 */
function checkPrivateFieldAccess({
  fieldLabel,
  typeDefinedInModulePath,
  currentModulePath,
  fieldToken,
}: {
  fieldLabel: string;
  typeDefinedInModulePath: string | undefined;
  currentModulePath: string | undefined;
  fieldToken: Token;
}): void {
  if (!fieldLabel.startsWith("_")) return;

  if (!typeDefinedInModulePath) return;
  if (!currentModulePath) return;

  // Auto-generated expansions inherit the privilege of the expansion site
  if (isAutoGeneratedExpansion(currentModulePath)) return;

  // Same file — always allowed
  if (currentModulePath === typeDefinedInModulePath) return;

  // Same directory — allowed
  const currentDir = currentModulePath.substring(
    0,
    currentModulePath.lastIndexOf("/")
  );
  const typeDefinedDir = typeDefinedInModulePath.substring(
    0,
    typeDefinedInModulePath.lastIndexOf("/")
  );
  if (currentDir === typeDefinedDir) return;

  // Same project root — allowed for in-project access across directories
  // (e.g., std/crypto/random.yo accessing String._bytes from std/string/).
  const projectDirs = ["/std/", "/tests/"];
  for (const marker of projectDirs) {
    const currentIdx = currentModulePath.indexOf(marker);
    const typeIdx = typeDefinedInModulePath.indexOf(marker);
    if (
      currentIdx >= 0 &&
      typeIdx >= 0 &&
      currentModulePath.substring(0, currentIdx) ===
        typeDefinedInModulePath.substring(0, typeIdx)
    ) {
      return;
    }
  }

  // Test batch files — the test framework creates synthetic batch files
  // that import and re-evaluate std/ types, causing module path mismatches
  // on both the accessing code side and the type's definedInModulePath side.
  if (
    currentModulePath.includes(".yo_test_batch_") ||
    typeDefinedInModulePath.includes(".yo_test_batch_")
  ) {
    return;
  }

  throw formatErrorMessage({
    token: fieldToken,
    errorMessage: `Cannot access private field '${fieldLabel}' on a type defined in '${typeDefinedInModulePath}'. Private fields (prefixed with '_') are only accessible within the file or directory that defines the containing type.`,
  });
}

export function evaluatePropertyAccess({
  expr,
  env,
  context,
}: {
  expr: FnCallExpr;
  env: Environment;
  context: EvaluatorContext;
}): FnCallExpr {
  if (!exprIsFunctionCallOf(expr, ".")) {
    throw formatErrorMessage({
      token: expr.token,
      errorMessage: `Expected "." for property access, got:\n${exprToString(expr)}`,
    });
  }

  // Short-circuit: Type.<KindName> is a kind-constraint syntactic form.
  // The result is the same TypeHierarchyType value `Type` alone returns,
  // letting `generic(E : Type.Struct, ...)` parse without a new keyword.
  if (
    exprIsFunctionCallOf(expr, ".", 2) &&
    exprIsAtom(expr.args[0]!) &&
    expr.args[0]!.token.value === "Type" &&
    exprIsAtom(expr.args[1]!) &&
    TYPE_KIND_REFINEMENTS.has(expr.args[1]!.token.value)
  ) {
    const typeAtom = expr.args[0]!;
    const evaluatedType = evaluateExpression({
      expr: typeAtom,
      env,
      context: { ...context, expectedType: undefined },
    });
    if (evaluatedType.$) {
      expr.$ = {
        env: evaluatedType.$.env,
        type: evaluatedType.$.type,
        value: evaluatedType.$.value,
        pathCollection: [],
      };
      expr.args[1]!.$ = expr.$;
      return expr;
    }
  }

  if (exprIsFunctionCallOf(expr, ".", 1)) {
    // Expect the argument to be an identifier
    const propertyExpr = expr.args[0]!;
    if (!exprIsAtom(propertyExpr) && !isValidVariableName(propertyExpr)) {
      throw formatErrorMessage({
        token: propertyExpr.token,
        errorMessage: `Expected identifier for enum variant access, got:\n${exprToString(
          propertyExpr
        )}`,
      });
    }

    const expectedEnumType = context.expectedType?.type;
    if (!isEnumType(expectedEnumType)) {
      throw formatErrorMessage({
        token: expr.token,
        errorMessage: `Failed to infer enum variant type.`,
      });
    }
    const variantName = propertyExpr.token.value;
    const enumType = expectedEnumType;

    const variant = enumType.variants.find(
      (_variant) => _variant.name === variantName
    );
    if (!variant) {
      throw formatErrorMessage({
        token: propertyExpr.token,
        errorMessage: `Enum variant "${variantName}" not found in enum`,
      });
    }
    const newEnumType: EnumType = {
      ...enumType,
      selectedVariantName: variantName,
    };

    /**
     * This is for case like
     * Color :: enum Red, Green, Blue;
     * r := Color.Red;
     */
    if (!variant.fields) {
      expr.$ = {
        env,
        type: newEnumType,
        // FIXME: Support expr.value for comptime evaluation.
        value: createEnumValue(newEnumType, variantName, []),
        pathCollection: [],
      };

      attachOwnedTempForRcUnitVariant(expr, newEnumType);

      propertyExpr.$ = {
        env: expr.$.env,
        type: newEnumType,
        pathCollection: [],
      };
    } else {
      /**
       * This is for case like
       * Shape := enum Circle(i32), Square(i32, i32);
       * c := Shape.Circle(3);
       */
      const enumTypeValue = createTypeValue(newEnumType);
      expr.$ = {
        env,
        value: enumTypeValue,
        type: enumTypeValue.type,
        pathCollection: [],
      };

      propertyExpr.$ = expr.$;
    }
    return expr;
  }

  if (!exprIsFunctionCallOf(expr, ".", 2)) {
    throw formatErrorMessage({
      token: expr.token,
      errorMessage: `Expected "." with 2 arguments, got:\n${exprToString(expr)}`,
    });
  }

  let objectExpr = expr.args[0]!;
  const propertyExpr = expr.args[1]!;

  // Evaluate object
  // Note: We don't pass expectedType when evaluating the object, because the expectedType
  // applies to the final property access result, not to the object itself.
  // For example, in `use_id(bi).*`, the expectedType might be i32, but use_id(bi) returns Box(i32).
  objectExpr = evaluateExpression({
    expr: objectExpr,
    env,
    context: { ...context, expectedType: undefined },
  });
  if (objectExpr.$?.env) {
    env = objectExpr.$?.env;
  }

  // NOTE: We shouldn't check borrowings here,
  // because it might be like:
  //   &(point.x); // point.x is borrowed
  //
  //   &(point.y) here objectExpr is Point, if we check borrowing here it will throw error.
  //
  // Check borrowings
  // checkBorrowings(context.borrowings, objectExpr);

  // Check if it's .* for dereference
  if (exprIsAtom(propertyExpr) && propertyExpr.token.value === "*") {
    if (isPtrType(objectExpr.$?.type)) {
      // Memory safety gate: pointer dereference requires `unsafe(...)`.
      // See plans/MEMORY_SAFETY.md. Files under std/ and yo-self/ are
      // implicitly unsafe-capable (Phase C will replace this with the
      // explicit pragma mechanism).
      if (
        !context.unsafeContext &&
        !isImplicitlyUnsafeCapableFile(propertyExpr.token.modulePath)
      ) {
        throw formatErrorMessage({
          token: propertyExpr.token,
          errorMessage: `Pointer dereference requires 'unsafe(...)'.

Wrap as: unsafe(${exprToString(objectExpr)}.*)

Raw pointer operations may dereference invalid memory.`,
        });
      }
      const pointerType = objectExpr.$.type;
      let baseType = pointerType.childType;

      // CRITICAL: If the child type is a SomeType, we need to resolve it from the environment
      // to get the properly constrained version (e.g., with where-clause constraints).
      // This is necessary because during function specialization, SomeTypes might be created
      // that reference the type parameter name but don't carry over the env-scoped constraints.
      // QUESTION: Is this correct? This fix is related to hash_set.yo
      if (isSomeType(baseType)) {
        baseType = getValueOfSomeTypeFromEnv(env, baseType);
      }

      // Check for compile-time pointer dereference
      const objectValue = objectExpr.$?.value;
      if (isPtrValue(objectValue)) {
        // For compile-time pointers, get the dereferenced value
        // If targetValue[0] is an ArrayValue, use targetIndex to get the element
        // Otherwise, targetValue[0] is the value itself (targetIndex should be 0)
        const target = objectValue.targetValue[0];
        let dereferencedValue: Value;
        if (isArrayValue(target)) {
          dereferencedValue = target.elements[objectValue.targetIndex]!;
        } else {
          dereferencedValue = target;
        }
        expr.$ = {
          env,
          type: baseType,
          value: dereferencedValue,
          originType: pointerType,
          isAccessingProperty: true,
          pathCollection: [],
          // Pass through the targetValue array so assignments can update it
          sourceVariable: objectExpr.$.sourceVariable,
        };
        // Store a reference to the pointer's targetValue and targetIndex for compile-time assignment
        (
          expr.$ as { ptrTargetValue?: [Value]; ptrTargetIndex?: number }
        ).ptrTargetValue = objectValue.targetValue;
        (
          expr.$ as { ptrTargetValue?: [Value]; ptrTargetIndex?: number }
        ).ptrTargetIndex = objectValue.targetIndex;
        propertyExpr.$ = expr.$;
        return expr;
      }

      // Handle UnknownValue for CTFE - dereference returns an UnknownValue of the base type
      if (isUnknownValue(objectValue)) {
        const dereferencedValue = createUnknownValue(baseType, {
          variableName: objectValue.variableName
            ? `${objectValue.variableName}.*`
            : undefined,
          env,
          context,
        });
        if (objectValue.isRuntimeOnly && isUnknownValue(dereferencedValue)) {
          dereferencedValue.isRuntimeOnly = true;
        }
        expr.$ = {
          env,
          type: baseType,
          value: dereferencedValue,
          originType: pointerType,
          isAccessingProperty: true,
          pathCollection: [],
        };
        propertyExpr.$ = expr.$;
        return expr;
      }

      expr.$ = {
        env,
        type: baseType,
        value: undefined,
        originType: pointerType, // Set origin type to the pointer type to track mutability path
        isAccessingProperty: true,
        pathCollection: [],
      };
      propertyExpr.$ = expr.$;

      // CRITICAL: Create a temp variable marked as NOT owning the RC value (borrowed).
      // This ensures that when this dereferenced value is returned from a function,
      // the ownership analysis in begin.ts will correctly identify it as borrowed
      // and insert a ___dup call. Without this, returning `self.*` from a function
      // would cause use-after-free bugs.
      attachTempVariableToExpr(expr, false);

      return expr;
    }

    // Not a pointer. The `.*` may still resolve later as a struct/object
    // field named `*` (e.g. `Box(T)` defines `(*) : V`) or as a `*`
    // method on the type's trait — fall through to the normal property
    // lookup. But if the type is one of the common cases that clearly
    // has no `*` member (the underlying type carries an
    // `indexTraitPtrType`, meaning the user wrote `value(idx).*` after
    // the Index trait already auto-dereferenced), surface a clear error
    // instead of the generic "Expected to be evaluated" failure that
    // appears farther downstream.
    if (objectExpr.$?.indexTraitPtrType) {
      const outputType = objectExpr.$.type;
      // If the Output type defines its own `*` member (e.g. Box(T)
      // declares `(*) : V`, or a trait declares a `*` method), fall
      // through to the normal property lookup so that legitimate
      // unwraps like `arr_of_boxes(0).*` keep working.
      const hasStarMember =
        (isStructType(outputType) &&
          outputType.fields?.some((f) => f.label === "*")) ||
        (isTraitType(outputType) &&
          outputType.fields?.some((f) => f.label === "*"));
      if (hasStarMember) {
        // Fall through to the normal struct/trait property lookup below.
      } else {
        throw formatErrorMessage({
          token: propertyExpr.token,
          errorMessage:
            `Cannot dereference value of type "${typeToString(outputType)}". ` +
            `The Index trait dispatch on this expression already returns the ` +
            `dereferenced element value (not a pointer), so the trailing ".*" ` +
            `is redundant. Drop the ".*" and chain the next call directly ` +
            `(e.g. \`value(idx).method()\`). ` +
            `If you intended to unwrap a smart pointer, the inner type "${typeToString(outputType)}" ` +
            `does not define a "*" member.`,
        });
      }
    }
  }

  if (isTypeValue(objectExpr.$?.value)) {
    const typeValue = objectExpr.$.value;
    if (isEnumType(typeValue.value)) {
      // Expect propertyExpr to be a symbol atom
      if (!exprIsAtom(propertyExpr)) {
        throw formatErrorMessage({
          token: propertyExpr.token,
          errorMessage: `Expected identifier for enum variant, got:\n${exprToString(propertyExpr)}`,
        });
      }

      // Check if it's accessing comptime field
      {
        const propertyName = propertyExpr.token.value;
        const field = typeValue.value.trait.fields.find(
          (method) => method.label === propertyName
        );
        if (field) {
          expr.$ = {
            env,
            type: field.type,
            value: field.assignedValue!,
            pathCollection: [],
            isAccessingProperty: true,
          };
          propertyExpr.$ = expr.$;
          return expr;
        }
      }

      const variantName = propertyExpr.token.value;
      // Check if variantName is a valid enum variant
      const enumType = typeValue.value;
      const variant = enumType.variants.find(
        (_variant) => _variant.name === variantName
      );
      if (!variant) {
        // Before throwing, check if the property is an impl'd method
        // (same pattern used for struct types at the generic impl lookup below)
        const genericMethods = findMethodsFromGenericImpls({
          concreteType: typeValue.value,
          methodName: variantName,
          env,
        });
        if (genericMethods.length === 1) {
          const method = genericMethods[0]!;
          expr.$ = {
            env,
            type: method.type,
            value: method.value,
            pathCollection: [],
            isAccessingProperty: true,
          };
          propertyExpr.$ = expr.$;
          return expr;
        }
        if (genericMethods.length > 1) {
          // Multiple matches — defer to function.ts for disambiguation
          expr.$ = undefined;
          return expr;
        }

        throw formatErrorMessage({
          token: propertyExpr.token,
          errorMessage: `Enum variant "${variantName}" not found in enum`,
        });
      }
      const newEnumType: EnumType = {
        ...enumType,
        selectedVariantName: variantName,
      };

      /**
       * This is for case like
       * Color :: enum Red, Green, Blue;
       * Red :: Color.Red;
       */
      if (!variant.fields) {
        expr.$ = {
          env,
          type: newEnumType,
          // FIXME: Support expr.value for comptime evaluation.
          value: createEnumValue(newEnumType, variantName, []),
          isAccessingProperty: true,
          pathCollection: [],
        };

        attachOwnedTempForRcUnitVariant(expr, newEnumType);

        propertyExpr.$ = expr.$;
      } else {
        /**
         * This is for case like
         * Shape := enum Circle(i32), Square(i32, i32);
         * c := Shape.Circle(3);
         */
        const enumTypeValue = createTypeValue(newEnumType);
        expr.$ = {
          env,
          type: enumTypeValue.type,
          value: enumTypeValue,
          isAccessingProperty: true,
          pathCollection: [],
        };

        propertyExpr.$ = expr.$;
      }
      return expr;
    }
    // Accessing comptime fields of a struct/union/dyn etc type.
    else if (typeValue.value.trait) {
      if (!isValidVariableName(propertyExpr)) {
        throw formatErrorMessage({
          token: propertyExpr.token,
          errorMessage: `Expected identifier for type method, got:\n${exprToString(propertyExpr)}`,
        });
      }
      const propertyName = propertyExpr.token.value;
      // Check if the type method exists
      // Use findLast to get the most recently added field (handles duplicates from impl blocks)
      const field = typeValue.value.trait.fields.findLast(
        (property) => property.label === propertyName
      );
      if (field) {
        // Phase P: private field access check
        checkPrivateFieldAccess({
          fieldLabel: propertyName,
          typeDefinedInModulePath: typeValue.value.definedInModulePath,
          currentModulePath:
            context.currentModulePath || propertyExpr.token.modulePath,
          fieldToken: propertyExpr.token,
        });

        // First check if the field has an assigned value (e.g., from impl providing Error : str)
        // This takes precedence over the unassignedSomeType placeholder
        if (field.assignedValue) {
          // Use the type from the assigned value
          const actualType = field.assignedValue.type;

          expr.$ = {
            env,
            type: actualType,
            value: field.assignedValue,
            pathCollection: [],
            isAccessingProperty: true,
          };
          propertyExpr.$ = expr.$;
          return expr;
        }

        // Check if this is an associated type (has unassignedSomeType but no assignedValue)
        // If so, return a TypeValue containing the SomeType placeholder
        if (field.unassignedSomeType) {
          const someTypeValue = createTypeValue(field.unassignedSomeType);
          expr.$ = {
            env,
            type: someTypeValue.type,
            value: someTypeValue,
            pathCollection: [],
            isAccessingProperty: true,
          };
          propertyExpr.$ = expr.$;
          return expr;
        }

        // Use field.type if no assigned value exists
        expr.$ = {
          env,
          type: field.type,
          value: undefined,
          pathCollection: [],
          isAccessingProperty: true,
        };
        propertyExpr.$ = expr.$;
        return expr;
      } else {
        // Property not found directly in type's own trait
        // Check impl'd trait values (fields with empty label that contain trait values)
        // These are created by impl(Type, Trait(...)) and contain associated type values
        // NOTE: Only resolve non-function values here (like associated types).
        // Function values (methods) should be deferred to function.ts for proper overload resolution.
        for (const implField of typeValue.value.trait.fields) {
          if (
            implField.label === "" &&
            implField.assignedValue &&
            isTraitValue(implField.assignedValue)
          ) {
            const implTraitValue = implField.assignedValue;
            const implTraitType = implTraitValue.type;
            // Search for the property in the impl'd trait
            const fieldIndex = implTraitType.fields.findIndex(
              (f) => f.label === propertyName
            );
            if (fieldIndex >= 0) {
              const traitField = implTraitType.fields[fieldIndex]!;
              const fieldValue = implTraitValue.fields[fieldIndex];

              // Skip function types - let function.ts handle method resolution
              // This allows proper overload resolution when multiple impls have the same method
              if (isFunctionType(traitField.type)) {
                continue;
              }

              if (fieldValue) {
                expr.$ = {
                  env,
                  type: fieldValue.type,
                  value: fieldValue,
                  pathCollection: [],
                  isAccessingProperty: true,
                };
                propertyExpr.$ = expr.$;
                return expr;
              } else if (traitField.unassignedSomeType) {
                // Associated type without assigned value
                const someTypeValue = createTypeValue(
                  traitField.unassignedSomeType
                );
                expr.$ = {
                  env,
                  type: someTypeValue.type,
                  value: someTypeValue,
                  pathCollection: [],
                  isAccessingProperty: true,
                };
                propertyExpr.$ = expr.$;
                return expr;
              }
            }
          }
        }

        // Check if there's a generic impl for this type (e.g., impl(generic(T), *(T), {...}))
        const genericMethods = findMethodsFromGenericImpls({
          concreteType: typeValue.value,
          methodName: propertyName,
          env,
        });
        // Only resolve here if there's exactly one match.
        // If there are multiple (e.g., multiple TryFrom implementations),
        // defer to function.ts which can resolve based on call arguments.
        if (genericMethods.length === 1) {
          const method = genericMethods[0]!;
          expr.$ = {
            env,
            type: method.type,
            value: method.value,
            pathCollection: [],
            isAccessingProperty: true,
          };
          propertyExpr.$ = expr.$;
          return expr;
        }

        // During generic impl specialization, the associated type (e.g., Output)
        // may already be bound in the env. Check there first, because
        // findAssociatedTypeFromGenericImpls is ambiguous when multiple impls
        // of the same trait exist with different associated types (e.g.,
        // Index(usize) with Output=T vs Index(Range(usize)) with Output=Slice(T)).
        if (context.isEvaluatingGenericImplSpecialization) {
          const vars = getVariablesFromEnv(env, propertyName);
          if (vars.length > 0) {
            const v = vars[vars.length - 1]!;
            if (v.value && v.value.length > 0 && isTypeValue(v.value[0])) {
              expr.$ = {
                env,
                type: v.value[0].type,
                value: v.value[0],
                pathCollection: [],
                isAccessingProperty: true,
              };
              propertyExpr.$ = expr.$;
              return expr;
            }
          }
        }

        // Check for associated types from generic impls (e.g., Self.Item from Iterator(T))
        const associatedType = findAssociatedTypeFromGenericImpls({
          concreteType: typeValue.value,
          propertyName,
          env,
        });
        if (associatedType) {
          expr.$ = {
            env,
            type: associatedType.type,
            value: associatedType.value,
            pathCollection: [],
            isAccessingProperty: true,
          };
          propertyExpr.$ = expr.$;
          return expr;
        }

        // Still not found - return undefined to allow function.ts
        // to handle this as a uniform function call (method call)
        // function.ts will call getTypeTraitMethodsByNameFromEnv to find the method
        // in implicit given implementations (like TypeMethods)
        expr.$ = undefined;
        return expr;
      }
    }
    // Accessing source namespace fields.
    else if (isSourceNamespaceType(typeValue.value)) {
      if (!isValidVariableName(propertyExpr)) {
        throw formatErrorMessage({
          token: propertyExpr.token,
          errorMessage: `Expected identifier for type method, got:\n${exprToString(propertyExpr)}`,
        });
      }
      const propertyName = propertyExpr.token.value;
      const sourceNamespaceType = typeValue.value;

      // Check if the type method exists in the module's own fields
      const field = sourceNamespaceType.fields.find(
        (property) => property.label === propertyName
      );
      if (field) {
        expr.$ = {
          env,
          type: field.type,
          value:
            field.assignedValue ??
            createUnknownValue(field.type, {
              variableName: field.label,
              env,
              context,
            }),
          pathCollection: [],
          isAccessingProperty: true,
        };
        propertyExpr.$ = expr.$;
        return expr;
      } else {
        // Property not found in type's own module
        // Return expr with expr.$ = undefined to allow function.ts
        // to handle this as a uniform function call (method call)
        // function.ts will call getTypeTraitMethodsByNameFromEnv to find the method
        // in implicit given implementations (like TypeMethods)
        expr.$ = undefined;
        return expr;
      }
    }
    // Access trait field
    else if (isTraitType(typeValue.value)) {
      if (!isValidVariableName(propertyExpr)) {
        throw formatErrorMessage({
          token: propertyExpr.token,
          errorMessage: `Expected identifier for type method, got:\n${exprToString(propertyExpr)}`,
        });
      }
      const propertyName = propertyExpr.token.value;
      const traitType = typeValue.value;

      // Special case: If the SourceNamespaceType has a receiverType set (from a subtype expression like (T <: PrintSelf)),
      // we need to look up the actual method implementation from the receiver type's trait.
      if (traitType.receiverType && traitType.receiverType.trait) {
        // Look for the impl'd trait that matches this trait type
        for (const field of traitType.receiverType.trait.fields) {
          if (
            field.label === "" &&
            field.assignedValue &&
            isTraitValue(field.assignedValue)
          ) {
            const implTraitValue = field.assignedValue;
            const implTraitType = implTraitValue.type;

            // Check if this impl trait matches our trait type using areTypesCompatible
            if (
              !areTypesCompatible(
                { type: traitType, env },
                { type: implTraitType, env }
              )
            ) {
              continue;
            }

            // Now look for the method in this matched impl trait
            const methodIndex = implTraitType.fields.findIndex(
              (f) => f.label === propertyName && isFunctionType(f.type)
            );
            if (methodIndex >= 0) {
              const method = implTraitType.fields[methodIndex]!;
              if (isFunctionType(method.type)) {
                // Get the actual function value from the trait value
                const methodValue = implTraitValue.fields[methodIndex];
                if (methodValue) {
                  // Use the function value's specialized type if available
                  let methodType = method.type;
                  if (
                    isFunctionValue(methodValue) &&
                    methodValue.specializedType
                  ) {
                    methodType = methodValue.specializedType;
                  }
                  expr.$ = {
                    env,
                    type: methodType,
                    value: methodValue,
                    pathCollection: [],
                    isAccessingProperty: true,
                  };
                  propertyExpr.$ = expr.$;
                  return expr;
                }
              }
            }
          }
        }

        // Not found in receiverType.trait.fields - try generic impl registry
        // This handles cases like `impl(generic(T : Type), Box(T), Isolation(...))`
        const genericMethod = findMethodFromGenericImplForTrait({
          concreteType: traitType.receiverType,
          traitType,
          methodName: propertyName,
          env,
        });
        if (genericMethod) {
          expr.$ = {
            env,
            type: genericMethod.type,
            value: genericMethod.value,
            pathCollection: [],
            isAccessingProperty: true,
          };
          propertyExpr.$ = expr.$;
          return expr;
        }
      }

      // Check if the type method exists in the trait's own fields
      const field = traitType.fields.find(
        (property) => property.label === propertyName
      );
      if (field) {
        expr.$ = {
          env,
          type: field.type,
          value:
            field.assignedValue ??
            createUnknownValue(field.type, {
              variableName: field.label,
              env,
              context,
            }),
          pathCollection: [],
          isAccessingProperty: true,
        };
        propertyExpr.$ = expr.$;
        return expr;
      } else {
        // Property not found in type's own trait
        // Return expr with expr.$ = undefined to allow function.ts
        // to handle this as a uniform function call (method call)
        // function.ts will call getTypeTraitMethodsByNameFromEnv to find the method
        // in implicit given implementations (like TypeMethods)
        expr.$ = undefined;
        return expr;
      }
    }
  }

  let objectType = objectExpr.$?.type;
  const originalObjectType = objectExpr.$?.type; // Capture before dereferencing

  // QUESTION: Should we allow only one round here? Like zig.
  while (objectType && isPtrType(objectType)) {
    // Dereference the pointer or reference type
    objectType = objectType.childType;
  }

  if (
    isTupleType(objectType) ||
    isStructType(objectType) ||
    isUnionType(objectType)
  ) {
    const fields: TypeField[] = objectType.fields;
    const objectExprValue = objectExpr.$!.value;

    // Check if it's accessing the tuple field by
    // - number index: point.0
    // - label name:   point.x
    if (exprIsAtom(propertyExpr)) {
      if (propertyExpr.token.type === TokenType.Integer) {
        // Accessing by index is only allowed for tuples.
        if (!isTupleType(objectExpr.$?.type)) {
          throw formatErrorMessage({
            token: propertyExpr.token,
            errorMessage: `Accessing tuple field by index is only allowed for tuples.`,
          });
        }

        const index = parseInt(propertyExpr.token.value, 10);
        if (isNaN(index)) {
          throw formatErrorMessage({
            token: propertyExpr.token,
            errorMessage: `Expected integer for tuple index, got:\n${exprToString(propertyExpr)}`,
          });
        }

        const fieldCount = fields.length;

        if (index < 0 || index >= fieldCount) {
          throw formatErrorMessage({
            token: propertyExpr.token,
            errorMessage: `Index out of bounds: ${index} for accessing field in:\n${typeToString(
              objectExpr.$?.type
            )}`,
          });
        }
        const tupleElement = fields[index]!;

        // Set origin type: use existing originType or the original object type
        const fieldOriginType = objectExpr.$.originType || originalObjectType;

        const indexPathCollection =
          objectExpr.$.pathCollection && objectExpr.$.pathCollection.length > 0
            ? objectExpr.$.pathCollection.map((p) => [
                ...p,
                propertyExpr.token.value,
              ])
            : [[objectExpr.$.variableName ?? "?", propertyExpr.token.value]];
        expr.$ = {
          env,
          type: tupleElement.type,
          originType: fieldOriginType,
          isAccessingProperty: true,
          pathCollection: indexPathCollection,
        };
        propertyExpr.$ = expr.$;

        // TODO: Support comptime value
        // expr.value = ...
        if (objectExprValue) {
          let values: (Value | undefined)[] = [];
          if (isTupleValue(objectExprValue)) {
            values = objectExprValue.fields;
          } else if (isStructValue(objectExprValue)) {
            values = objectExprValue.fields;
          }
          expr.$.value = values?.[index];
        }

        attachTempVariableToExpr(expr, false); // NOTE: This should not take the ownership of the value

        return expr;
      } else if (isValidVariableName(propertyExpr)) {
        const label = propertyExpr.token.value;
        {
          const tupleFieldIndex = fields.findIndex(
            // NOTE: To access comptime only field, use the type instead, not the value.
            // The value can only access runtime fields.
            (field) => field.label === label
          );
          if (tupleFieldIndex < 0) {
            if (isSourceNamespaceType(objectExpr.$?.type)) {
              throw formatErrorMessage({
                token: propertyExpr.token,
                errorMessage: `Record field "${label}" not found in source namespace type`,
              });
            }

            // It could be method call
            expr.$ = undefined;
            return expr;
          }

          // Phase P: private field access check
          checkPrivateFieldAccess({
            fieldLabel: label,
            typeDefinedInModulePath: objectType.definedInModulePath,
            currentModulePath:
              context.currentModulePath || propertyExpr.token.modulePath,
            fieldToken: propertyExpr.token,
          });

          const tupleElement = fields[tupleFieldIndex]!;

          // Set origin type: use existing originType or the original object type
          const fieldOriginType =
            objectExpr.$?.originType || originalObjectType;

          const labelPathCollection =
            objectExpr.$!.pathCollection &&
            objectExpr.$!.pathCollection.length > 0
              ? objectExpr.$!.pathCollection.map((p) => [
                  ...p,
                  propertyExpr.token.value,
                ])
              : [[objectExpr.$!.variableName ?? "?", propertyExpr.token.value]];
          expr.$ = {
            env,
            type: tupleElement.type,
            originType: fieldOriginType,
            isAccessingProperty: true,
            pathCollection: labelPathCollection,
          };
          propertyExpr.$ = expr.$;

          // TODO: Support comptime value
          // expr.value = ...
          if (objectExprValue) {
            if (isUnknownValue(objectExprValue)) {
              const fieldUnknown = createUnknownValue(tupleElement.type, {
                env,
                context,
              });
              if (
                objectExprValue.isRuntimeOnly &&
                isUnknownValue(fieldUnknown)
              ) {
                fieldUnknown.isRuntimeOnly = true;
              }
              expr.$.value = fieldUnknown;
            } else {
              // Deref PtrValue if accessing a field through a comptime pointer
              let resolvedValue: Value = objectExprValue;
              if (isPtrValue(objectExprValue)) {
                const target = objectExprValue.targetValue[0]!;
                if (isArrayValue(target)) {
                  resolvedValue = target.elements[objectExprValue.targetIndex]!;
                } else {
                  // For struct/other pointers, the target IS the value.
                  // Field selection is handled by tupleFieldIndex below.
                  resolvedValue = target;
                }
              }

              let values: (Value | undefined)[] = [];
              if (isTupleValue(resolvedValue)) {
                values = resolvedValue.fields;
              } else if (isStructValue(resolvedValue)) {
                values = resolvedValue.fields;
              }

              let value = values?.[tupleFieldIndex];
              if (!value) {
                value = createUnknownValue(tupleElement.type, { env, context });
              }

              expr.$.value = value;

              // Set comptimeRef for comptime field access through a pointer.
              // This enables mutation via assignment (p(0) = value) and &(self.x) in ComptimeIndex.
              if (isPtrValue(objectExprValue)) {
                if (isStructValue(resolvedValue)) {
                  expr.$.comptimeRef = {
                    kind: "struct",
                    structValue: resolvedValue,
                    fieldIndex: tupleFieldIndex,
                  };
                } else if (isTupleValue(resolvedValue)) {
                  expr.$.comptimeRef = {
                    kind: "tuple",
                    tupleValue: resolvedValue,
                    fieldIndex: tupleFieldIndex,
                  };
                }
              }
            }
          }

          attachTempVariableToExpr(expr, false); // NOTE: This should not take the ownership of the value

          return expr;
        }
      }
    }
  } else if (isSourceNamespaceType(objectType)) {
    const fields: TypeField[] = objectType.fields;
    const objectExprValue = objectExpr.$!.value;

    // Check if it's accessing the tuple field by
    // - label name:   SomeModule.some_function
    if (exprIsAtom(propertyExpr)) {
      if (propertyExpr.token.type === TokenType.Integer) {
        throw formatErrorMessage({
          token: propertyExpr.token,
          errorMessage: `Accessing source namespace fields by index is not allowed, got:\n${exprToString(
            propertyExpr
          )}`,
        });
      } else if (isValidVariableName(propertyExpr)) {
        const label = propertyExpr.token.value;

        {
          const recordFieldIndex = fields.findIndex(
            (field) => field.label === label
          );
          if (recordFieldIndex < 0) {
            if (isSourceNamespaceType(objectExpr.$?.type)) {
              // Check if this module is still being evaluated (circular import).
              // If so, the field might exist but hasn't been exported yet.
              if (
                objectExprValue &&
                isStructValue(objectExprValue) &&
                objectExprValue.isLoading
              ) {
                throw formatErrorMessage({
                  token: propertyExpr.token,
                  errorMessage: `Field "${label}" is not yet available from this module. In a circular import, only fields exported before the import of the current module are accessible. Reorder your exports or break the cycle.`,
                });
              }
              throw formatErrorMessage({
                token: propertyExpr.token,
                errorMessage: `Record field "${label}" not found in source namespace type`,
              });
            }

            // It could be method call
            expr.$ = undefined;
            return expr;
          }
          const recordField = fields[recordFieldIndex]!;
          const modulePathCollection =
            objectExpr.$!.pathCollection &&
            objectExpr.$!.pathCollection.length > 0
              ? objectExpr.$!.pathCollection.map((p) => [
                  ...p,
                  propertyExpr.token.value,
                ])
              : [[objectExpr.$!.variableName ?? "?", propertyExpr.token.value]];
          expr.$ = {
            env,
            type: recordField.type,
            isAccessingProperty: true,
            pathCollection: modulePathCollection,
          };
          propertyExpr.$ = expr.$;

          // TODO: Support comptime value
          // expr.value = ...
          if (objectExprValue) {
            if (isUnknownValue(objectExprValue)) {
              const fieldUnknown = createUnknownValue(recordField.type, {
                env,
                context,
              });
              if (
                objectExprValue.isRuntimeOnly &&
                isUnknownValue(fieldUnknown)
              ) {
                fieldUnknown.isRuntimeOnly = true;
              }
              expr.$.value = fieldUnknown;
            } else {
              let values: (Value | undefined)[] = [];
              if (isStructValue(objectExprValue)) {
                values = objectExprValue.fields;
              }

              let value = values?.[recordFieldIndex];
              if (!value) {
                value = createUnknownValue(recordField.type, { env, context });
              }

              expr.$.value = value;
            }
          }
          return expr;
        }
      }
    }
  } else if (isEnumType(objectType)) {
    if (exprIsAtom(propertyExpr)) {
      if (!isValidVariableName(propertyExpr)) {
        throw formatErrorMessage({
          token: propertyExpr.token,
          errorMessage: `Expected identifier for enum variant property, got:\n${exprToString(
            propertyExpr
          )}`,
        });
      }

      const propertyName = propertyExpr.token.value;
      const selectedVariant = objectType.variants.find(
        (variant) => variant.name === objectType.selectedVariantName
      );
      if (selectedVariant) {
        // Check if the property exists in the selected variant
        const fieldIndex = (selectedVariant.fields ?? []).findIndex(
          (property) => property.label === propertyName
        );
        if (fieldIndex < 0) {
          /*
          throw formatErrorMessage({
            token: propertyExpr.token,
            errorMessage: `Enum variant property "${propertyName}" not found in enum variant "${objectType.selectedVariantName}"`,
          });
          */
          // It could be method call
          expr.$ = undefined;
          return expr;
        }

        const field = (selectedVariant.fields ?? [])[fieldIndex]!;

        expr.$ = {
          env,
          type: field.type,
          value: undefined,
          pathCollection: [
            [
              objectExpr.$!.variableName ?? "?", // FIXME
              propertyExpr.token.value,
            ],
          ],
          isAccessingProperty: true,
        };

        // handle comptime value
        const variantValue = objectExpr.$?.value;
        if (
          variantValue &&
          isEnumValue(variantValue) &&
          variantValue.variantName === selectedVariant.name
        ) {
          expr.$.value = variantValue.fields[fieldIndex];
        }

        propertyExpr.$ = expr.$;

        return expr;
      } else {
        // No `selectedVariantName` — the enum isn't narrowed to a variant (e.g.
        // a bare `fn(e : E)` parameter, whose runtime variant isn't statically
        // known). Resolve the property against the variant that declares it,
        // when exactly one does, so `e.field` / `e.field = x` works the same as
        // struct-field access (a `ref(struct)` parameter already supports
        // in-place field mutation; a `ref(enum)` parameter must too — reference
        // semantics). The programmer asserts the active variant; codegen emits
        // the unchecked `->data.<Variant>.<field>` access. Ambiguous field
        // names or non-field property names fall through, preserving the
        // enum-method-call path below.
        const declaringVariants = objectType.variants.filter((v) =>
          (v.fields ?? []).some((f) => f.label === propertyName)
        );
        if (declaringVariants.length === 1) {
          const variant = declaringVariants[0]!;
          const fieldIndex = (variant.fields ?? []).findIndex(
            (f) => f.label === propertyName
          );
          const field = (variant.fields ?? [])[fieldIndex]!;
          expr.$ = {
            env,
            type: field.type,
            value: undefined,
            pathCollection: [
              [objectExpr.$!.variableName ?? "?", propertyExpr.token.value],
            ],
            isAccessingProperty: true,
          };
          const variantValue = objectExpr.$?.value;
          if (
            variantValue &&
            isEnumValue(variantValue) &&
            variantValue.variantName === variant.name
          ) {
            expr.$.value = variantValue.fields[fieldIndex];
          }
          propertyExpr.$ = expr.$;
          return expr;
        }
        // Otherwise it could be an enum method call, so we ignore here.
      }
    }
  }

  // TODO: Evaluate the module method call
  // Since we fail to evaluate the property access
  // it could be an ~~uniform function call~~ module method call.
  expr.$ = undefined;
  return expr;
}
