#!/usr/bin/env bash
# Yo language installer for Linux and macOS.
#
# Installs Yo into $HOME/.local/Yo and links the `yo` command into
# $HOME/.local/bin (or a directory of your choice via $YO_BIN_DIR).
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/shd101wyy/yo/main/scripts/install.sh | bash
#   # or, after cloning:
#   ./scripts/install.sh
#
# Environment variables:
#   YO_INSTALL_DIR   Target install dir.   Default: $HOME/.local/Yo
#   YO_BIN_DIR       Wrapper bin dir.      Default: $HOME/.local/bin
#   YO_REPO          Git repo URL.         Default: https://github.com/shd101wyy/yo.git
#   YO_REF           Git ref (branch/tag). Default: main
#   YO_FORCE         If set, overwrite existing install dir.

set -euo pipefail

YO_INSTALL_DIR="${YO_INSTALL_DIR:-$HOME/.local/Yo}"
YO_BIN_DIR="${YO_BIN_DIR:-$HOME/.local/bin}"
YO_REPO="${YO_REPO:-https://github.com/shd101wyy/yo.git}"
YO_REF="${YO_REF:-main}"

color() { printf '\033[%sm%s\033[0m' "$1" "$2"; }
info()  { printf '%s %s\n' "$(color '1;34' '>>')" "$1"; }
warn()  { printf '%s %s\n' "$(color '1;33' '!!')" "$1" >&2; }
err()   { printf '%s %s\n' "$(color '1;31' 'XX')" "$1" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Detect platform
# ---------------------------------------------------------------------------

OS="$(uname -s)"
case "$OS" in
  Linux)  PLATFORM="linux"  ;;
  Darwin) PLATFORM="macos"  ;;
  *) err "Unsupported OS: $OS. This installer supports Linux and macOS only." ;;
esac

info "Installing Yo on $PLATFORM"
info "Install dir: $YO_INSTALL_DIR"
info "Bin dir:     $YO_BIN_DIR"

# ---------------------------------------------------------------------------
# Required tools
# ---------------------------------------------------------------------------

need() {
  command -v "$1" >/dev/null 2>&1 || err "Missing required command: $1"
}

need git
need curl

# C compiler (clang or gcc) — needed for `yo compile`.
if ! command -v clang >/dev/null 2>&1 && ! command -v gcc >/dev/null 2>&1; then
  warn "No C compiler found (clang or gcc). 'yo compile' will not work until you install one."
  if [ "$PLATFORM" = "macos" ]; then
    warn "  Install with: xcode-select --install"
  else
    warn "  Install with your distro's package manager (e.g. apt install clang)"
  fi
fi

# bun runtime — required to run the current TypeScript-based compiler.
if ! command -v bun >/dev/null 2>&1; then
  info "bun not found — installing via official installer..."
  curl -fsSL https://bun.sh/install | bash
  # Try common bun install locations
  for candidate in "$HOME/.bun/bin" "$HOME/.local/share/bun/bin"; do
    if [ -x "$candidate/bun" ]; then
      export PATH="$candidate:$PATH"
      break
    fi
  done
  command -v bun >/dev/null 2>&1 || err "bun installation failed — install manually from https://bun.sh"
fi
info "Using bun: $(command -v bun) ($(bun --version))"

# ---------------------------------------------------------------------------
# Download Yo
# ---------------------------------------------------------------------------

if [ -e "$YO_INSTALL_DIR" ]; then
  if [ -n "${YO_FORCE:-}" ]; then
    info "Removing existing install dir (YO_FORCE set)"
    rm -rf "$YO_INSTALL_DIR"
  else
    err "Install dir already exists: $YO_INSTALL_DIR. Set YO_FORCE=1 to overwrite."
  fi
fi

info "Cloning $YO_REPO ($YO_REF) into $YO_INSTALL_DIR"
mkdir -p "$(dirname "$YO_INSTALL_DIR")"
git clone --depth 1 --branch "$YO_REF" "$YO_REPO" "$YO_INSTALL_DIR"

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

info "Installing dependencies (bun install)"
( cd "$YO_INSTALL_DIR" && bun install --silent )

info "Building Yo (bun run build)"
( cd "$YO_INSTALL_DIR" && bun run build )

# ---------------------------------------------------------------------------
# Wrapper script
# ---------------------------------------------------------------------------

mkdir -p "$YO_BIN_DIR"
WRAPPER="$YO_BIN_DIR/yo"

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Yo language CLI — auto-generated by install.sh
set -euo pipefail
exec "$YO_INSTALL_DIR/yo-cli" "\$@"
EOF
chmod +x "$WRAPPER"

info "Installed wrapper: $WRAPPER"

# ---------------------------------------------------------------------------
# PATH check
# ---------------------------------------------------------------------------

case ":$PATH:" in
  *":$YO_BIN_DIR:"*) ;;
  *)
    warn "$YO_BIN_DIR is not on your PATH."
    warn "Add this to your shell rc file (.bashrc / .zshrc / etc):"
    warn "    export PATH=\"\$HOME/.local/bin:\$PATH\""
    ;;
esac

info "Done. Try: yo --help"
