#!/usr/bin/env bash
#
# Build ONE portable `yo.c` from the per-target C emissions.
#
# Why concatenation rather than a merged file
# -------------------------------------------
# Each arm is a COMPLETE translation unit for its platform, wrapped in a
# preprocessor conditional. The C preprocessor selects exactly one; the rest are
# skipped without being tokenized. This is deliberate, and it is the *safe*
# design rather than a compromise — see plans/PORTABLE_C_DISTRIBUTION.md:
#
#   * A genuinely MERGED file (one copy of the shared ~99%, `#if` only at the
#     divergences) decouples the two halves of every platform constant. The Yo
#     half is frozen at emit time; the C half would be chosen at C-compile time.
#     They agree today only because one emitter run picks both for one target.
#     Decoupled, `symlink_metadata` silently calls stat() instead of lstat() on
#     the wrong pairing — and it still compiles, links and runs.
#   * Concatenated, each arm keeps its Yo half and C half from the SAME emitter
#     run, so that class of bug cannot occur, and detect_host() is right in each.
#
# Measured (2026-08-15, macOS arm64): a 5-arm file of 713,346,156 bytes /
# 11,280,738 lines compiles in 69.34 s versus 68.65 s for one arm alone — 568 MB
# of skipped arms cost 0.7 s — and the resulting binary passes `check`.
#
# THE TRAP this script exists to get right
# ----------------------------------------
# The emitted .c does NOT end with a newline. A naive
# `{ cat a.c; echo '#else'; cat b.c; }` therefore produces `}#else`, which is
# not a directive at all (a directive must start a line). Both arms then compile
# and you get a flood of redefinition errors that looks exactly like the whole
# approach failing. Every directive below is emitted with a leading newline.
#
# Usage:
#   scripts/make-portable-c.sh <out.c> <dir-with-per-target-c-files>
#
# Expected inputs in <dir> (missing arms are allowed and become #error arms):
#   linux-x64.c  linux-arm64.c  macos-x64.c  macos-arm64.c  windows-x64.c
set -euo pipefail

OUT="${1:?usage: make-portable-c.sh <out.c> <dir>}"
DIR="${2:?usage: make-portable-c.sh <out.c> <dir>}"

emit_arm() {
  # $1 = file, $2 = human-readable platform name for the #error fallback
  local f="$DIR/$1" name="$2"
  if [ -s "$f" ]; then
    cat "$f" >> "$OUT"
    printf '\n' >> "$OUT"   # the trap above: guarantee the next directive starts a line
  else
    printf '#error "Yo: this portable yo.c was built without a %s arm"\n' "$name" >> "$OUT"
  fi
}

directive() { printf '%s\n' "$1" >> "$OUT"; }

mkdir -p "$(dirname "$OUT")"
: > "$OUT"

directive "/* Portable single-file Yo compiler."
directive " *"
directive " * Generated by scripts/make-portable-c.sh — do not edit."
directive " * Contains one complete C translation unit per supported platform;"
directive " * the preprocessor selects the one matching your machine."
directive " *"
directive " * Build (Linux/macOS):"
directive " *   cc -std=c11 -fno-strict-aliasing -fwrapv -w -O2 yo.c -o yo -lpthread -lm"
directive " * On Linux, install liburing headers first or async I/O is unavailable."
directive " */"

directive "#if defined(_WIN32)"
emit_arm "windows-x64.c" "windows-x64"

directive "#elif defined(__APPLE__)"
directive "#  if defined(__aarch64__) || defined(__arm64__)"
emit_arm "macos-arm64.c" "macos-arm64"
directive "#  else"
emit_arm "macos-x64.c" "macos-x64"
directive "#  endif"

directive "#elif defined(__linux__)"
directive "#  if defined(__aarch64__)"
emit_arm "linux-arm64.c" "linux-arm64"
directive "#  else"
emit_arm "linux-x64.c" "linux-x64"
directive "#  endif"

directive "#else"
directive "#  error \"Yo: unsupported platform — no arm in this portable yo.c\""
directive "#endif"

BYTES=$(wc -c < "$OUT")
LINES=$(wc -l < "$OUT")
echo "wrote $OUT: $BYTES bytes, $LINES lines"

# A file whose arms silently went missing still "succeeds" as a concatenation,
# so report which arms are real. A caller publishing this can gate on the count.
for f in linux-x64 linux-arm64 macos-x64 macos-arm64 windows-x64; do
  if [ -s "$DIR/$f.c" ]; then echo "  arm present: $f"; else echo "  arm MISSING: $f (becomes #error)"; fi
done
