/**
 * Memory-safety helpers (Phase C of plans/MEMORY_SAFETY.md).
 *
 * Per-file privilege tracking via `pragma(Pragma.AllowUnsafe);`. When
 * the `pragma` builtin is evaluated, it records the file's URI in the
 * `privilegedFiles` registry. The pointer-op gates then look up the
 * current expression's source file in this registry — files that
 * declared the pragma bypass the unsafe-wrap requirement.
 *
 * This replaces the Phase A MVP path-based heuristic. The only
 * remaining bypass is `auto-generated://...` URIs (macro/derive
 * expansions), which inherit the surrounding file's privilege via
 * the expansion site.
 */

import { writeFileSync } from "node:fs";

/** Pragma flags a file can declare. */
export type PragmaKind =
  | "AllowUnsafe"
  | "SkipPrelude"
  | "SkipWasm"
  | "SkipWasm32Emscripten"
  | "SkipWasm32Wasi"
  // Formal verification pragmas — Phase 0 just registers them.
  // See plans/FORMAL_VERIFICATION.md.
  | "Verify"
  | "VerifyOrAssert"
  | "NoContracts";

/**
 * Per-file pragma registry. Keyed by canonical module URI (the
 * value of `token.modulePath`, e.g. `file:///path/to/foo.yo`).
 */
const privilegedFiles: Map<string, Set<PragmaKind>> = new Map();

/** Record that `modulePath` declared `pragma(Pragma.X);`. */
export function registerFilePragma(modulePath: string, kind: PragmaKind): void {
  let set = privilegedFiles.get(modulePath);
  if (!set) {
    set = new Set();
    privilegedFiles.set(modulePath, set);
  }
  set.add(kind);
}

/** Has `modulePath` declared a given pragma? */
export function fileHasPragma(
  modulePath: string | undefined,
  kind: PragmaKind
): boolean {
  if (!modulePath) return false;
  const set = privilegedFiles.get(modulePath);
  return !!set && set.has(kind);
}

/** Reset the registry. Used by tests and the LSP between sessions. */
export function _clearPragmaRegistry(): void {
  privilegedFiles.clear();
}

/**
 * Drop pragma entries for a single module. Called when an LSP edit
 * (or any other module-level invalidation) removes a file from the
 * cache so the file's previous privileges don't leak into the next
 * evaluation of the same URI — e.g. a user editing `pragma(...)` out
 * of an existing file.
 */
export function _clearPragmaForModule(modulePath: string): void {
  privilegedFiles.delete(modulePath);
}

/**
 * Is the module path implicitly unsafe-capable for pointer ops?
 *
 * Returns true if:
 * - The file declared `pragma(Pragma.AllowUnsafe);` at the top, OR
 * - The expression came from compiler-synthesized code (macros,
 *   derive expansions) whose URI is `auto-generated://...`. These
 *   originate from a privileged caller; the wrap policy of the
 *   expanded code is the caller's responsibility.
 *
 * User code that hasn't declared the pragma must wrap pointer
 * operations in `unsafe(...)` explicitly.
 */
export function isImplicitlyUnsafeCapableFile(
  modulePath: string | undefined
): boolean {
  if (!modulePath) return false;
  if (modulePath.startsWith("auto-generated://")) return true;
  return fileHasPragma(modulePath, "AllowUnsafe");
}

/**
 * Is this module path a compiler-synthesized expansion (macro, derive,
 * prelude desugaring)? Such URIs are tagged `auto-generated://...` and
 * inherit their privilege from the user-facing call site that
 * triggered the expansion.
 *
 * Used by the extern-call `unsafe(...)` gate (plans/archive/EXTERN_UNSAFE_WRAP.md):
 * a macro that expands into an `extern "c"` call should NOT force the
 * user's expansion site to wrap each generated call in `unsafe(...)`;
 * the macro author owns that contract.
 *
 * Distinct from `isImplicitlyUnsafeCapableFile`, which also accepts
 * pragma'd files. The extern-call gate wants the auto-generated
 * exemption WITHOUT the pragma exemption.
 */
export function isAutoGeneratedExpansion(
  modulePath: string | undefined
): boolean {
  if (!modulePath) return false;
  return modulePath.startsWith("auto-generated://");
}

/**
 * Migration helper for plans/archive/EXTERN_UNSAFE_WRAP.md Phase C.
 *
 * When the env var `YO_EXTERN_WRAP_DUMP_FILE` is set, the extern-call
 * gate records each unwrapped call site here instead of throwing. The
 * collected entries are flushed to the dump file on process exit, so
 * a single `./yo-cli check ./std` run produces the complete migration
 * worklist. The Phase C script reads the JSON and applies precise
 * `unsafe(...)` wraps.
 */
type ExternCallSiteRecord = {
  modulePath: string;
  characterOffset: number;
  calleeName: string;
};

const externCallSites: ExternCallSiteRecord[] = [];
let externCallExitHookInstalled = false;

export function recordExternCallSite(record: ExternCallSiteRecord): void {
  externCallSites.push(record);
  if (!externCallExitHookInstalled) {
    externCallExitHookInstalled = true;
    const dumpPath = process.env.YO_EXTERN_WRAP_DUMP_FILE;
    if (dumpPath) {
      process.on("exit", () => {
        // Synchronous write is required in the 'exit' handler.
        writeFileSync(dumpPath, JSON.stringify(externCallSites, null, 2));
      });
    }
  }
}
