/**
 * Lock file management for Yo dependency resolution.
 *
 * Format (`yo.lock`):
 * ```
 * [[dependencies]]
 * name = "json-parser"
 * url = "https://github.com/user/json-parser.git"
 * ref = "v1.0.0"
 * commit = "abc123..."
 * hash = "sha256-XXXXX..."
 *
 * [[dependencies]]
 * name = "http-client"
 * url = "https://github.com/user/http-client.git"
 * ref = "main"
 * commit = "def456..."
 * hash = "sha256-YYYYY..."
 * ```
 */

import * as fs from "fs";
import * as path from "path";

export interface LockEntry {
  name: string;
  url: string;
  ref: string;
  commit: string;
  hash: string;
}

export interface LockFile {
  dependencies: LockEntry[];
}

/**
 * Parse a `yo.lock` file into a structured representation.
 */
export function parseLockFile(content: string): LockFile {
  const dependencies: LockEntry[] = [];
  const lines = content.split("\n");

  let current: Partial<LockEntry> | undefined;

  for (const rawLine of lines) {
    const line = rawLine.trim();

    if (line === "" || line.startsWith("#")) {
      continue;
    }

    if (line === "[[dependencies]]") {
      if (current && current.name) {
        dependencies.push(finalizeLockEntry(current));
      }
      current = {};
      continue;
    }

    if (current === undefined) {
      continue;
    }

    const eqIdx = line.indexOf("=");
    if (eqIdx === -1) continue;

    const key = line.slice(0, eqIdx).trim();
    let value = line.slice(eqIdx + 1).trim();

    // Strip surrounding quotes
    if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
      value = value.slice(1, -1);
    }

    switch (key) {
      case "name":
        current.name = value;
        break;
      case "url":
        current.url = value;
        break;
      case "ref":
        current.ref = value;
        break;
      case "commit":
        current.commit = value;
        break;
      case "hash":
        current.hash = value;
        break;
    }
  }

  // Push last entry
  if (current && current.name) {
    dependencies.push(finalizeLockEntry(current));
  }

  return { dependencies };
}

function finalizeLockEntry(partial: Partial<LockEntry>): LockEntry {
  return {
    name: partial.name ?? "",
    url: partial.url ?? "",
    ref: partial.ref ?? "HEAD",
    commit: partial.commit ?? "",
    hash: partial.hash ?? "",
  };
}

/**
 * Serialize a lock file to string.
 */
export function writeLockFileContent(lockFile: LockFile): string {
  const sections: string[] = [];

  // Header comment
  sections.push(
    "# This file is auto-generated by `yo fetch`. Do not edit manually."
  );
  sections.push("");

  for (const dep of lockFile.dependencies) {
    const block = [
      "[[dependencies]]",
      `name = "${dep.name}"`,
      `url = "${dep.url}"`,
      `ref = "${dep.ref}"`,
      `commit = "${dep.commit}"`,
      `hash = "${dep.hash}"`,
    ].join("\n");
    sections.push(block);
  }

  return sections.join("\n\n") + "\n";
}

/**
 * Read and parse a `yo.lock` file from a project directory.
 * Returns an empty lock file if the file does not exist.
 */
export function readLockFile(projectDir: string): LockFile {
  const lockPath = path.join(projectDir, "yo.lock");
  if (!fs.existsSync(lockPath)) {
    return { dependencies: [] };
  }
  const content = fs.readFileSync(lockPath, "utf-8");
  return parseLockFile(content);
}

/**
 * Write a lock file to a project directory.
 */
export function saveLockFile(projectDir: string, lockFile: LockFile): void {
  const lockPath = path.join(projectDir, "yo.lock");
  fs.writeFileSync(lockPath, writeLockFileContent(lockFile), "utf-8");
}

/**
 * Find a lock entry by dependency name.
 */
export function findLockEntry(
  lockFile: LockFile,
  name: string
): LockEntry | undefined {
  return lockFile.dependencies.find((d) => d.name === name);
}

/**
 * Update or insert a lock entry.
 */
export function upsertLockEntry(
  lockFile: LockFile,
  entry: LockEntry
): LockFile {
  const existing = lockFile.dependencies.findIndex(
    (d) => d.name === entry.name
  );
  const deps = [...lockFile.dependencies];
  if (existing >= 0) {
    deps[existing] = entry;
  } else {
    deps.push(entry);
  }
  return { dependencies: deps };
}
