name: Test Module Manager

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install liburing
      run: |
        sudo apt-get update
        sudo apt-get install -y liburing-dev

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: |
        bun install
        bun install -g @vscode/vsce
        bun run build
    - name: Run tests
      run: ./yo-cli test ./tests --bail -v
  
    - name: Bundle vscode extension
      run: |
        cd vscode-extension
        bun install
        bun run build
        bun package